//! What a client does when a call that changes something did not answer.
//!
//! A+ gate 5 asks one question of every capability an agent can reach: does it
//! support safe retry and deduplication, or does it declare that it cannot be
//! retried and give enough readback to reconcile an uncertain outcome? The
//! descriptors answer half of that — each publishes an
//! [`IdempotencyPolicy`] — and `gateway/idempotency.rs` enforces it. The other
//! half had no home: *which read* tells a client whether its lost
//! `annotate.label.create` landed was written in prose beside the capability,
//! if anywhere, and nothing failed when a new capability arrived without one.
//!
//! This module is that home, and each family module is where a row is
//! written: `analysis` declares the drawings' rows beside `DRAWINGS_SCOPE_ID`,
//! `trade` the ticket's beside `TICKET_EVENT_KIND`, and [`FAMILIES`] is the
//! declared list [`READBACKS`] joins at compile time. A row states the policy
//! its capability is expected to declare, the read capability (and the
//! snapshot scope or journal event kind) that shows its effect, the field in
//! that read, what that field says when the call applied, and the transport
//! test that proves the row. `docs/control-plane/retry-matrix.md` is the
//! registry rendered through those rows by `quantick-app --dump-retry-matrix`,
//! the way the capability inventory beside it is rendered. Row order never
//! reaches that document: the renderer walks the registry and asks each
//! capability for its row.
//!
//! # What is derived and what is written
//!
//! Derived from the registry, never written by hand: which capabilities are
//! mutable, the policy each declares, what the gateway therefore does with a
//! key, and whether any grant reaches the capability at all. Written in the
//! family module, because no registry knows it: which read reconciles a call. [`drift`] is what keeps the written half
//! honest against the derived half — a mutable capability with no row, a row
//! for nothing, a declared policy the descriptor no longer publishes, a
//! readback capability or scope the registry does not carry or that can
//! change state, a read with a scope or event kind it does not take, a
//! snapshot field the scope's own published schema does not have, or a
//! readback a caller granted the capability could not read. The generator
//! refuses to render while any of those stands. A journal row's field has no
//! published schema to check against — event payloads are not registered —
//! so it is proven where it is used instead: the transport tests read every
//! journal row's field back from a real event.
//!
//! # Cost
//!
//! None at run time. The table is `const` data; [`drift`] and the renderer run
//! only from `main`'s dump path, before a window exists, and from tests.

mod drift;
mod reach;
mod render;
mod rows;

pub use crate::readback::*;
pub use drift::{
    Drift, MAX_SCHEMA_HOPS, branches, drift, read_needs, readable, row_drift, schema_has_path,
};
pub use reach::{Holder, ceiling, holder, profiles_in_ceiling_order};
pub use render::{PREAMBLE, RenderedRow, enforced, policy_name, render, summary};
pub use rows::{FAMILIES, READBACKS, readback};

/// The banner the generated file opens with. Load-bearing, as the inventory's
/// is: `crates/guards` greps for it to confirm it is reading generated output.
pub const GENERATED_MARKER: &str =
    "<!-- generated by `quantick-app --dump-retry-matrix`; do not edit -->";
