//! The registry half of the launch hooks: the declared slices joined into
//! one catalogue, the names an environment sets that nothing declares, and
//! the generated registry document fused from the declarations and the
//! authored prose.
//!
//! Everything here is a function of what it is handed — the owners table
//! the application keeps, the not-a-hook table beside it, the prose text —
//! so the application's `hooks` module is the table and the startup
//! warning, and this is the mechanism.

use std::collections::BTreeSet;

use super::HookSpec;

/// Every declared hook, with the file that owns it, in name order.
pub fn all(
    owners: &[(&'static str, &'static [HookSpec])],
) -> Vec<(&'static str, &'static HookSpec)> {
    let mut out: Vec<(&'static str, &'static HookSpec)> = owners
        .iter()
        .flat_map(|(path, specs)| specs.iter().map(move |spec| (*path, spec)))
        .collect();
    out.sort_by_key(|(_, spec)| spec.name);
    out
}

/// Every declared hook name.
pub fn declared_names(owners: &[(&'static str, &'static [HookSpec])]) -> BTreeSet<&'static str> {
    owners
        .iter()
        .flat_map(|(_, specs)| specs.iter().map(|spec| spec.name))
        .collect()
}

/// The `QUANTICK_*` variables set in this environment that no slice declares.
///
/// Takes the environment as an iterator rather than reading it, so the test
/// can exercise the real comparison without touching process state — setting
/// an environment variable is `unsafe` in this edition and racy under a
/// threaded test runner.
pub fn unknown_hooks<'a>(
    environment: impl Iterator<Item = &'a str>,
    declared: &BTreeSet<&'static str>,
    not_hooks: &[(&str, &str)],
) -> Vec<String> {
    let mut out: Vec<String> = environment
        .filter(|name| name.starts_with("QUANTICK_"))
        .filter(|name| !declared.contains(name))
        .filter(|name| !not_hooks.iter().any(|(known, _)| known == name))
        .map(str::to_owned)
        .collect();
    out.sort();
    out.dedup();
    out
}

/// The marker the generated registry opens with.
pub const GENERATED_MARKER: &str =
    "<!-- generated by `quantick-app --dump-hook-registry`; do not edit -->";

/// The path a reader opens, with the part every hook shares taken off.
///
/// `crates/app/src/` in front of a hundred and twenty-nine rows is two
/// kilobytes of the context budget spent saying the same eleven words, in a
/// file whose whole argument is that a targeted run should cost less to
/// answer, not more.
pub const OWNER_PREFIX: &str = "crates/app/src/";

/// Fuse the declared hooks into the authored prose.
///
/// Hook rows retain their authored order and complete descriptions.
/// Repeated owner paths use readable keys; the legend resolves each key
/// to its full path. Single-use paths remain in their rows. The legend
/// contains owner paths only, so it never duplicates the hook inventory.
///
/// Prose lines that are not table rows pass through untouched, and a row's
/// `Reaches` cell is never rewritten — the authored prose file is the authored half and
/// this function is not allowed an opinion about it.
pub fn render_registry(hooks: &[(&'static str, &'static HookSpec)], prose: &str) -> String {
    let owners: std::collections::BTreeMap<&str, &'static str> = hooks
        .iter()
        .map(|(path, spec)| (spec.name, path.strip_prefix(OWNER_PREFIX).unwrap_or(path)))
        .collect();

    let mut out = String::new();
    out.push_str("# Hook registry\n\n");
    out.push_str(GENERATED_MARKER);
    out.push_str("\n\n");
    out.push_str(concat!(
        "Declared `QUANTICK_*` inputs: behavior, feature requirements and owners.
",
        "Paths relative to `crates/app/src/`; declaration does not enable a hook.
",
        "
",
        "Generated: owner `declare_hooks!` slices include disabled hooks,
",
        "prose from `docs/ui-harness/hook-prose.md` — edit there, then
",
        "`cargo run -p quantick-app -- --dump-hook-registry > <this file>`.
",
        "`cargo test -p quantick-guards` checks source/declaration/prose parity;
",
        "disabled hooks remain cataloged. Undeclared, non-exempt names in the
",
        "environment are logged at startup as `UNKNOWN_HOOK`.
",
        "
",
    ));

    // The prose file opens with its own explanation of what it is and how to
    // regenerate from it. That is guidance for whoever edits it, not part of
    // the registry, and the generated file states both things in its own
    // words above — so the copy starts at the first table.
    let body = match prose.find("\n| Hook ") {
        Some(offset) => &prose[offset + 1..],
        None => prose,
    };

    let keys = owner_keys(&owners, body);
    if !keys.is_empty() {
        out.push_str(
            "\nOwner keys (other paths appear in full):\n\n| Key | Declared in |\n| --- | --- |\n",
        );
        for (path, key) in &keys {
            out.push_str(&format!("| {key} | `{path}` |\n"));
        }
        out.push('\n');
    }
    for line in body.lines() {
        if line.starts_with("| Hook ") {
            out.push_str("| Hook | Owner | Reaches |\n");
        } else if line.starts_with("| --- ") {
            out.push_str("| --- | --- | --- |\n");
        } else if let Some(fused) = fuse_row(line, &owners, &keys) {
            out.push_str(&fused);
            out.push('\n');
        } else {
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!("\n{} hooks registered.\n", hooks.len()));
    out
}

/// Readable presentation keys; full paths remain canonical in the legend.
pub fn owner_keys(
    owners: &std::collections::BTreeMap<&str, &'static str>,
    body: &str,
) -> std::collections::BTreeMap<&'static str, String> {
    let mut counts = std::collections::BTreeMap::<&str, usize>::new();
    for line in body.lines() {
        if let Some((_, _, paths)) = row_paths(line, owners) {
            for path in paths {
                *counts.entry(path).or_default() += 1;
            }
        }
    }
    let mut assigned: std::collections::BTreeMap<_, _> = owners
        .values()
        .map(|path| (*path, (*path).to_owned()))
        .collect();
    for path in assigned.keys().copied().collect::<Vec<_>>() {
        let key = owner_key_candidates(path)
            .into_iter()
            .find(|key| {
                assigned
                    .iter()
                    .all(|(other, value)| *other == path || value != key)
            })
            .expect("the exact owner path is unique");
        assigned.insert(path, key);
    }
    assigned.retain(|path, _| counts.get(path).is_some_and(|count| *count > 1));
    assigned
}

pub fn owner_key_candidates(path: &str) -> Vec<String> {
    let stem = path
        .strip_suffix("/mod.rs")
        .or_else(|| path.strip_suffix("/src/lib.rs"))
        .unwrap_or_else(|| path.strip_suffix(".rs").unwrap_or(path));
    let parts: Vec<_> = stem.split('/').collect();
    let words: Vec<_> = parts
        .last()
        .expect("a path has a segment")
        .split('_')
        .collect();
    let mut candidates: Vec<_> = (1..=words.len())
        .map(|length| words[words.len() - length..].join("_"))
        .collect();
    candidates.extend((2..=parts.len()).map(|length| parts[parts.len() - length..].join("/")));
    candidates.push(path.to_owned());
    candidates
}

/// Keep complete cells and the order of distinct owners within each row.
pub fn row_paths<'a>(
    line: &'a str,
    owners: &std::collections::BTreeMap<&str, &'static str>,
) -> Option<(&'a str, &'a str, Vec<&'static str>)> {
    let body = line.strip_prefix("| ")?.strip_suffix(" |")?;
    let (hook_cell, reaches) = body.split_once(" | ")?;
    let mut paths = Vec::new();
    for name in hook_names(hook_cell) {
        if let Some(path) = owners.get(name.as_str())
            && !paths.contains(path)
        {
            paths.push(*path);
        }
    }
    Some((hook_cell, reaches, paths))
}

pub fn fuse_row(
    line: &str,
    owners: &std::collections::BTreeMap<&str, &'static str>,
    keys: &std::collections::BTreeMap<&str, String>,
) -> Option<String> {
    let (hook_cell, reaches, paths) = row_paths(line, owners)?;
    let owner_cell = if paths.is_empty() {
        "—".to_owned()
    } else {
        paths
            .iter()
            .map(|path| {
                keys.get(path)
                    .cloned()
                    .unwrap_or_else(|| format!("`{path}`"))
            })
            .collect::<Vec<_>>()
            .join(", ")
    };
    Some(format!("| {hook_cell} | {owner_cell} | {reaches} |"))
}

/// Every `QUANTICK_*` named in a cell, in order of appearance.
pub fn hook_names(cell: &str) -> Vec<String> {
    let bytes = cell.as_bytes();
    let mut out = Vec::new();
    let mut index = 0;
    while let Some(offset) = cell[index..].find("QUANTICK_") {
        let start = index + offset;
        let mut end = start;
        while end < bytes.len()
            && (bytes[end].is_ascii_uppercase()
                || bytes[end].is_ascii_digit()
                || bytes[end] == b'_')
        {
            end += 1;
        }
        out.push(cell[start..end].to_owned());
        index = end;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn readable_owners_preserve_complete_cells_notes_modes_and_missing_owners() {
        static A: HookSpec = HookSpec::new("QUANTICK_ALPHA");
        static B: HookSpec = HookSpec::new("QUANTICK_BETA");
        let hooks = [
            ("crates/app/src/first_owner.rs", &A),
            ("crates/app/src/second_owner.rs", &B),
        ];
        let prose = "Intro\n| Hook | Reaches |\n| --- | --- |\n\
            | `QUANTICK_ALPHA=one` | Complete \\| escaped pipe, `code`, and Unicode — kept. |\n\
            Notes stay between these rows.\n\
            | `QUANTICK_BETA` / `QUANTICK_ALPHA=two` | Both owners, in this order. |\n\
            | `QUANTICK_MISSING` | Missing stays missing. |\n";
        let rendered = render_registry(&hooks, prose);
        assert!(rendered.contains("| owner | `first_owner.rs` |"));
        assert!(rendered.contains("| `QUANTICK_ALPHA=one` | owner | Complete \\| escaped pipe, `code`, and Unicode — kept. |"));
        assert!(rendered.contains("| `QUANTICK_BETA` / `QUANTICK_ALPHA=two` | `second_owner.rs`, owner | Both owners, in this order. |"));
        assert!(rendered.contains("| `QUANTICK_MISSING` | — | Missing stays missing. |"));
        let first = rendered.find("`QUANTICK_ALPHA=one`").unwrap();
        let note = rendered.find("Notes stay between these rows.").unwrap();
        let second = rendered.find("`QUANTICK_BETA` / ").unwrap();
        assert!(first < note && note < second);
        assert_eq!(rendered.matches("`QUANTICK_ALPHA=one`").count(), 1);
        assert_eq!(rendered.matches("`QUANTICK_ALPHA=two`").count(), 1);
    }

    #[test]
    fn owner_keys_are_deterministic_and_avoid_singleton_and_basename_collisions() {
        static A: HookSpec = HookSpec::new("QUANTICK_ALPHA");
        static B: HookSpec = HookSpec::new("QUANTICK_BETA");
        static C: HookSpec = HookSpec::new("QUANTICK_GAMMA");
        let hooks = [
            ("crates/app/src/a/shared_owner.rs", &A),
            ("crates/app/src/b/shared_owner.rs", &B),
            ("crates/app/src/c/shared_owner.rs", &C),
        ];
        let prose = "| Hook | Reaches |\n| --- | --- |\n\
            | `QUANTICK_ALPHA=one` | A one. |\n\
            | `QUANTICK_ALPHA=two` | A two. |\n\
            | `QUANTICK_BETA` | B singleton. |\n\
            | `QUANTICK_GAMMA=one` | C one. |\n\
            | `QUANTICK_GAMMA=two` | C two. |\n";
        let rendered = render_registry(&hooks, prose);
        assert_eq!(
            rendered,
            render_registry(&[hooks[2], hooks[0], hooks[1]], prose)
        );
        assert!(rendered.contains("| owner | `a/shared_owner.rs` |"));
        assert!(rendered.contains("| c/shared_owner | `c/shared_owner.rs` |"));
        assert!(rendered.contains("| `QUANTICK_BETA` | `b/shared_owner.rs` | B singleton. |"));
        assert!(
            !rendered.contains("| shared_owner |"),
            "the singleton reserves this readable key"
        );
    }

    #[test]
    fn owner_key_candidates_normalize_modules_and_keep_exact_fallback() {
        assert_eq!(
            owner_key_candidates("surfaces/drawing_chrome/mod.rs"),
            [
                "chrome",
                "drawing_chrome",
                "surfaces/drawing_chrome",
                "surfaces/drawing_chrome/mod.rs"
            ]
        );
        assert_eq!(
            owner_key_candidates("crates/feed/src/lib.rs"),
            ["feed", "crates/feed", "crates/feed/src/lib.rs"]
        );
        assert_eq!(owner_key_candidates("plain.rs"), ["plain", "plain.rs"]);
    }

    #[test]
    fn singleton_or_missing_owners_need_no_legend() {
        static A: HookSpec = HookSpec::new("QUANTICK_ALPHA");
        let rendered = render_registry(
            &[("crates/app/src/one.rs", &A)],
            "| Hook | Reaches |\n| --- | --- |\n| `QUANTICK_ALPHA` | One. |\n| `QUANTICK_MISSING` | None. |\n",
        );
        assert!(!rendered.contains("Owner keys"));
        assert!(rendered.contains("| `QUANTICK_ALPHA` | `one.rs` | One. |"));
        assert!(rendered.contains("| `QUANTICK_MISSING` | — | None. |"));
    }

    #[test]
    fn an_exact_path_remains_available_when_every_short_key_is_taken() {
        let owners = std::collections::BTreeMap::from([
            ("QUANTICK_ALPHA", "a/foo.rs"),
            ("QUANTICK_BETA", "foo.rs"),
        ]);
        let body = "| `QUANTICK_ALPHA=one` | A. |\n| `QUANTICK_ALPHA=two` | A. |\n\
            | `QUANTICK_BETA=one` | B. |\n| `QUANTICK_BETA=two` | B. |\n";
        let keys = owner_keys(&owners, body);
        assert_eq!(keys["a/foo.rs"], "foo");
        assert_eq!(keys["foo.rs"], "foo.rs");
    }

    #[test]
    fn keys_reconstruct_each_distinct_owner_in_original_row_order() {
        let owners = std::collections::BTreeMap::from([
            ("QUANTICK_ALPHA", "a/owner.rs"),
            ("QUANTICK_BETA", "b/owner.rs"),
        ]);
        let body = "| `QUANTICK_BETA` / `QUANTICK_ALPHA` | Both. |\n\
            | `QUANTICK_ALPHA` / `QUANTICK_BETA` | Reverse. |\n";
        let keys = owner_keys(&owners, body);
        let reverse: std::collections::BTreeMap<_, _> = keys
            .iter()
            .map(|(path, key)| (key.as_str(), *path))
            .collect();
        assert_eq!(reverse.len(), keys.len(), "no two paths share a key");
        for (line, expected) in body.lines().zip([
            vec!["b/owner.rs", "a/owner.rs"],
            vec!["a/owner.rs", "b/owner.rs"],
        ]) {
            let rendered = fuse_row(line, &owners, &keys).unwrap();
            let owner_cell = rendered.split(" | ").nth(1).unwrap();
            let reconstructed: Vec<_> = owner_cell.split(", ").map(|key| reverse[key]).collect();
            assert_eq!(reconstructed, expected);
        }
    }
}
