//! Literal specimens cover the cheap guard's supported declaration grammar.
//! The app's existing registry comparisons remain the generation authority.

#[path = "../src/scratch_dir.rs"]
mod scratch_dir;

use std::{fs, path::Path};

use quantick_guards::{generated, workspace_root};
use scratch_dir::ScratchDir;

// Expected IDs, rows, counts and diagnostics are authored independently of the
// production scanner and renderer. Each declaration uses the documented
// one-line *_CAPABILITY_ID grammar; inline registrations are outside this test.
const ONE_CAPABILITY: &str = "\
<!-- generated by `quantick-app --dump-capability-inventory`; do not edit -->
| Capability | Version | Module | Read-only | Permissions |
| --- | --- | --- | --- | --- |
| `chart.summary.read` | 1 | `chart` | yes | `observe.chart` |

1 capabilities registered.
";

const TWO_CAPABILITIES: &str = "\
<!-- generated by `quantick-app --dump-capability-inventory`; do not edit -->
| Capability | Version | Module | Read-only | Permissions |
| --- | --- | --- | --- | --- |
| `chart.summary.read` | 1 | `chart` | yes | `observe.chart` |
| `orderflow.l2.read` | 1 | `orderflow` | yes | `observe.orderflow` |

2 capabilities registered.
";

// A behaviour matrix naming the one capability the inventory above carries,
// and one row that records an exclusion instead. Authored here rather than
// generated, so the guard is measured against a document it did not write.
const ONE_BEHAVIOUR: &str = "\
<!-- generated by `quantick-app --dump-ui-behaviour-matrix`; do not edit -->
| Behaviour | What it does | Reach | Capability | Exclusion |
| --- | --- | --- | --- | --- |
| `chart.summary.read` | Read the summary | toolbar | `chart.summary.read` | — |
| `app.exit` | Close it | File menu | — | `authority` — a stated ceiling |
";

fn fixture() -> ScratchDir {
    let root = ScratchDir::new("capability-documentation");
    for directory in [
        "crates/app/src/control",
        "crates/feed/src",
        "docs/control-plane",
        "docs/ui-harness",
        ".claude/skills/ui-harness/references",
    ] {
        fs::create_dir_all(root.join(directory)).unwrap();
    }
    fs::write(
        root.join("crates/app/src/control/chart.rs"),
        "const SUMMARY_CAPABILITY_ID: &str = \"chart.summary.read\";\n",
    )
    .unwrap();
    fs::write(root.join(generated::INVENTORY_PATH), ONE_CAPABILITY).unwrap();
    fs::write(root.join(generated::MATRIX_PATH), ONE_BEHAVIOUR).unwrap();
    // The public check also checks hooks. Supply all its inputs rather than
    // filter their findings out of the capability assertions.
    fs::write(
        root.join(generated::REGISTRY_PATH),
        "<!-- generated by `quantick-app --dump-hook-registry`; do not edit -->\n",
    )
    .unwrap();
    fs::write(root.join(generated::PROSE_PATH), "# No launch hooks\n").unwrap();
    fs::write(
        root.join("crates/app/src/hooks.rs"),
        "const NOT_HOOKS: &[&str] = &[\n    \"QUANTICK_FIXTURE_CONFIG\",\n];\n",
    )
    .unwrap();
    assert!(generated::check(&root).is_empty(), "baseline must be valid");
    root
}

fn assert_only_finding(root: &Path, expected: &str) {
    let findings = generated::check(root);
    let lines: Vec<&str> = findings
        .iter()
        .map(|finding| finding.line.as_str())
        .collect();
    assert_eq!(lines, [expected], "the complete finding set must match");
}

#[test]
fn the_next_owner_requires_documentation_and_removal_leaves_an_orphan() {
    let root = fixture();
    let owner = root.join("crates/app/src/control/orderflow.rs");
    fs::write(
        &owner,
        "const L2_CAPABILITY_ID: &str = \"orderflow.l2.read\";\n",
    )
    .unwrap();
    assert_only_finding(
        &root,
        "crates/app/src/control/orderflow.rs:1: `orderflow.l2.read` is registered but has no row in docs/control-plane/capability-inventory.md",
    );

    fs::write(root.join(generated::INVENTORY_PATH), TWO_CAPABILITIES).unwrap();
    assert!(
        generated::check(&root).is_empty(),
        "the literal second row and footer repair the documentation"
    );

    fs::write(&owner, "").unwrap();
    assert_only_finding(
        &root,
        "docs/control-plane/capability-inventory.md:5: `orderflow.l2.read` is documented but no `*_CAPABILITY_ID` constant under crates/app/src/control declares it",
    );
}

#[test]
fn missing_generated_marker_is_reported() {
    let root = fixture();
    let without_marker = ONE_CAPABILITY.split_once('\n').unwrap().1;
    fs::write(root.join(generated::INVENTORY_PATH), without_marker).unwrap();
    assert_only_finding(
        &root,
        "docs/control-plane/capability-inventory.md: no generated-by marker; this file must not be hand-written",
    );
}

#[test]
fn stale_footer_is_reported() {
    let root = fixture();
    fs::write(
        root.join(generated::INVENTORY_PATH),
        ONE_CAPABILITY.replace("1 capabilities registered.", "2 capabilities registered."),
    )
    .unwrap();
    assert_only_finding(
        &root,
        "docs/control-plane/capability-inventory.md: the footer claims 2 capabilities but the table has 1 rows",
    );
}

#[test]
fn missing_inventory_is_reported() {
    let root = fixture();
    fs::remove_file(root.join(generated::INVENTORY_PATH)).unwrap();
    assert_only_finding(
        &root,
        "docs/control-plane/capability-inventory.md: missing — the generated capability inventory is not there",
    );
}

/// A matrix row naming a capability the inventory does not carry is the drift
/// a capability rename causes, and it is reported without building the app.
#[test]
fn a_matrix_row_naming_an_unregistered_capability_is_reported() {
    let root = fixture();
    fs::write(
        root.join(generated::MATRIX_PATH),
        ONE_BEHAVIOUR.replace("`chart.summary.read` |", "`chart.summary.peek` |"),
    )
    .unwrap();
    assert_only_finding(
        &root,
        "docs/control-plane/ui-behaviour-matrix.md: a row maps a behaviour to `chart.summary.peek`, which docs/control-plane/capability-inventory.md does not register",
    );
}

#[test]
fn a_matrix_that_lost_its_marker_is_reported() {
    let root = fixture();
    let without_marker = ONE_BEHAVIOUR.split_once('\n').unwrap().1;
    fs::write(root.join(generated::MATRIX_PATH), without_marker).unwrap();
    assert_only_finding(
        &root,
        "docs/control-plane/ui-behaviour-matrix.md: the generated marker line is gone",
    );
}

#[test]
fn a_missing_matrix_is_reported() {
    let root = fixture();
    fs::remove_file(root.join(generated::MATRIX_PATH)).unwrap();
    assert_only_finding(
        &root,
        "docs/control-plane/ui-behaviour-matrix.md: missing — the generated UI behaviour matrix is not there",
    );
}

#[test]
fn agent_orientation_links_to_existing_canonical_outputs() {
    let root = workspace_root();
    let agents = fs::read_to_string(root.join("AGENTS.md")).unwrap();
    for target in [
        "docs/control-plane/capability-inventory.md",
        "schemas/control/observer-capability-catalog-v1.json",
    ] {
        assert!(agents.contains(&format!("]({target})")), "link to {target}");
        assert!(root.join(target).is_file(), "link resolves: {target}");
    }
    let inventory = fs::read_to_string(root.join(generated::INVENTORY_PATH)).unwrap();
    assert!(
        inventory.contains(
            "<!-- generated by `quantick-app --dump-capability-inventory`; do not edit -->"
        )
    );
    // Preserve the discoverable entry point without freezing its prose.
    assert!(agents.contains("`quantick_describe`"));
}
