//! The capability inventory, rendered from a registry rather than written
//! beside it: the rows `docs/control-plane/capability-inventory.md` carries,
//! in the order the registry keeps them, so two runs cannot disagree.

use std::fmt::Write as _;

use quantick_control::registry::CapabilityDescriptor;

/// The banner the generated file opens with.
///
/// Load-bearing rather than decorative: the guard greps for the marker line to
/// confirm it is reading a generated file and not a hand-written one that
/// happens to share the path.
pub const GENERATED_MARKER: &str =
    "<!-- generated by `quantick-app --dump-capability-inventory`; do not edit -->";

/// Render the inventory for these capabilities.
#[must_use]
pub fn render(capabilities: &[&CapabilityDescriptor]) -> String {
    let mut out = String::new();
    out.push_str("# Control plane capability inventory\n\n");
    out.push_str(GENERATED_MARKER);
    out.push_str("\n\n");
    out.push_str(concat!(
        "Every capability the running application registers, as the registry\n",
        "reports it. This file is generated; a hand edit is a guard failure, not\n",
        "a correction. To change a row, change the capability and regenerate:\n",
        "\n",
        "```sh\n",
        "cargo run -p quantick-app -- --dump-capability-inventory \\\n",
        "  > docs/control-plane/capability-inventory.md\n",
        "```\n",
        "\n",
        "`cargo test -p quantick-guards` fails when this file and the registry\n",
        "disagree, which is why it can be trusted where the prose it replaced\n",
        "could not. See [Precedence](README.md#precedence) for which of the two\n",
        "wins when they do disagree — the answer is never this file.\n",
        "\n",
        "**Version** is the number an invocation must ask for; a capability may\n",
        "register more than one. **Permissions** are the scopes a connection has\n",
        "to hold, all of them, before the call is admitted; a capability with no\n",
        "scope listed is reachable by any connected client. **Read-only** marks a\n",
        "capability that cannot change application state.\n",
        "\n",
    ));

    let _ = writeln!(
        out,
        "| Capability | Version | Module | Read-only | Permissions |"
    );
    let _ = writeln!(out, "| --- | --- | --- | --- | --- |");
    for capability in capabilities {
        let permissions = if capability.required_permissions.is_empty() {
            "—".to_owned()
        } else {
            capability
                .required_permissions
                .iter()
                .map(|permission| format!("`{}`", permission.as_str()))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            out,
            "| `{}` | {} | `{}` | {} | {} |",
            capability.id.as_str(),
            capability.version,
            capability.module.as_str(),
            if capability.read_only { "yes" } else { "no" },
            permissions,
        );
    }

    let _ = write!(out, "\n{} capabilities registered.\n", capabilities.len());
    out
}
