//! The capability inventory, rendered from the registry rather than written
//! beside it.
//!
//! `docs/control-plane/capability-inventory.md` used to be prose. It was
//! measured once, at `fcd2ac4`, and by the time anyone read it again the
//! registry had moved 476 commits and the document had not: it listed
//! capabilities that do not exist and omitted most of the ones that do. A
//! reader could not tell which half they were holding.
//!
//! So the file is now output. [`capability_inventory_markdown`] walks the same
//! [`ObserverContract`](super::contract::ObserverContract) the gateway serves
//! and renders every registered capability with the four facts a caller needs
//! before it can invoke one — the identifier, the version it must ask for, the
//! module that owns it, and the permissions the connection must hold. Three
//! things keep the committed copy honest:
//!
//! - `quantick-app --dump-capability-inventory` writes it, so regenerating is
//!   a named command rather than a manual edit.
//! - A test in `crates/app` compares the committed file against this function,
//!   which is the authoritative check: it holds the real registry.
//! - `crates/guards/src/generated.rs` compares the committed file against the
//!   `*_CAPABILITY_ID` constants textually, which is the *fast* check: no
//!   dependencies, no build of this crate, and it runs in the same second as
//!   the rest of the guards.
//!
//! The fast check exists because the authoritative one lives behind the
//! slowest crate in the repository. An agent that adds a capability and
//! forgets to regenerate learns it from `cargo test -p quantick-guards`
//! seconds later, not from CI twenty minutes later.

use std::fmt::Write as _;

use quantick_control::registry::CapabilityDescriptor;

use super::contract::ObserverContract;

/// The banner the generated file opens with.
///
/// Load-bearing rather than decorative: the guard greps for the marker line to
/// confirm it is reading a generated file and not a hand-written one that
/// happens to share the path.
pub(crate) const GENERATED_MARKER: &str =
    "<!-- generated by `quantick-app --dump-capability-inventory`; do not edit -->";

/// Render the committed contents of
/// `docs/control-plane/capability-inventory.md`.
///
/// Deterministic by construction: the registry stores capabilities in a
/// `BTreeMap` keyed by `(id, version)`, so the row order is the identifier
/// order and two runs of this function on the same tree cannot disagree. That
/// is what lets the committed copy be compared byte for byte instead of
/// parsed.
pub(crate) fn capability_inventory_markdown() -> Result<String, String> {
    let projections =
        super::standard_registry().map_err(|error| format!("projection registry: {error}"))?;
    let actions =
        super::actions::standard_actions().map_err(|error| format!("action registry: {error}"))?;
    let contract = ObserverContract::new(
        &projections,
        std::sync::Arc::new(actions),
        super::evidence::EvidenceStore::new(),
    )
    .map_err(|error| format!("observer contract: {error}"))?;

    let capabilities: Vec<&CapabilityDescriptor> = contract.registry().capabilities().collect();
    Ok(render(&capabilities))
}

fn render(capabilities: &[&CapabilityDescriptor]) -> String {
    let mut out = String::new();
    out.push_str("# Control plane capability inventory\n\n");
    out.push_str(GENERATED_MARKER);
    out.push_str("\n\n");
    out.push_str(concat!(
        "Every capability the running application registers, as the registry\n",
        "reports it. This file is generated; a hand edit is a guard failure, not\n",
        "a correction. To change a row, change the capability and regenerate:\n",
        "\n",
        "```sh\n",
        "cargo run -p quantick-app -- --dump-capability-inventory \\\n",
        "  > docs/control-plane/capability-inventory.md\n",
        "```\n",
        "\n",
        "`cargo test -p quantick-guards` fails when this file and the registry\n",
        "disagree, which is why it can be trusted where the prose it replaced\n",
        "could not. See [Precedence](README.md#precedence) for which of the two\n",
        "wins when they do disagree — the answer is never this file.\n",
        "\n",
        "**Version** is the number an invocation must ask for; a capability may\n",
        "register more than one. **Permissions** are the scopes a connection has\n",
        "to hold, all of them, before the call is admitted; a capability with no\n",
        "scope listed is reachable by any connected client. **Read-only** marks a\n",
        "capability that cannot change application state.\n",
        "\n",
    ));

    let _ = writeln!(
        out,
        "| Capability | Version | Module | Read-only | Permissions |"
    );
    let _ = writeln!(out, "| --- | --- | --- | --- | --- |");
    for capability in capabilities {
        let permissions = if capability.required_permissions.is_empty() {
            "—".to_owned()
        } else {
            capability
                .required_permissions
                .iter()
                .map(|permission| format!("`{}`", permission.as_str()))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            out,
            "| `{}` | {} | `{}` | {} | {} |",
            capability.id.as_str(),
            capability.version,
            capability.module.as_str(),
            if capability.read_only { "yes" } else { "no" },
            permissions,
        );
    }

    let _ = write!(out, "\n{} capabilities registered.\n", capabilities.len());
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The authoritative check: the committed file is what this generator
    /// emits today, byte for byte, against the real registry.
    ///
    /// `crates/guards` cannot make this comparison — it has no dependencies
    /// and therefore no registry — so it compares identifier sets textually
    /// instead. That catches the common mistake in one second; this catches
    /// every mistake, including a permission added to a capability that
    /// already had a row, which moves no identifier and so is invisible to a
    /// set comparison.
    #[test]
    fn the_committed_inventory_is_what_the_generator_emits() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(std::path::Path::parent)
            .expect("crates/app sits two levels below the workspace root")
            .join("docs/control-plane/capability-inventory.md");
        let committed = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));
        assert_eq!(
            committed,
            capability_inventory_markdown().expect("the registry builds"),
            "the committed capability inventory is stale. Regenerate it:\n  \
             cargo run -p quantick-app -- --dump-capability-inventory > \
             docs/control-plane/capability-inventory.md"
        );
    }

    /// Every row carries the four facts a caller needs before it can invoke a
    /// capability. A generator that silently dropped a column would still pass
    /// the byte comparison above, because that test regenerates the file it is
    /// comparing against.
    #[test]
    fn every_row_carries_identifier_version_module_and_permissions() {
        let markdown = capability_inventory_markdown().expect("the registry builds");
        let rows: Vec<&str> = markdown
            .lines()
            .filter(|line| line.starts_with("| `"))
            .collect();
        assert!(!rows.is_empty(), "the inventory rendered no capabilities");
        for row in rows {
            let columns: Vec<&str> = row.trim_matches('|').split('|').collect();
            assert_eq!(columns.len(), 5, "row has the wrong column count: {row}");
            assert!(columns[0].trim().starts_with('`'), "no identifier: {row}");
            assert!(
                columns[1].trim().parse::<u32>().is_ok(),
                "version is not a number: {row}"
            );
            assert!(columns[2].trim().starts_with('`'), "no module: {row}");
            assert!(
                matches!(columns[3].trim(), "yes" | "no"),
                "read-only is not a yes/no: {row}"
            );
        }
    }
}
