//! What a client does when a call that changes something did not answer.
//!
//! A+ gate 5 asks one question of every capability an agent can reach: does it
//! support safe retry and deduplication, or does it declare that it cannot be
//! retried and give enough readback to reconcile an uncertain outcome? The
//! descriptors answer half of that — each publishes an
//! [`IdempotencyPolicy`] — and `gateway/idempotency.rs` enforces it. The other
//! half had no home: *which read* tells a client whether its lost
//! `annotate.label.create` landed was written in prose beside the capability,
//! if anywhere, and nothing failed when a new capability arrived without one.
//!
//! This module is that home. [`READBACKS`] holds one row per mutable
//! capability: the policy it is expected to declare, the read capability (and
//! the snapshot scope or journal event kind) that shows its effect, the field
//! in that read, what that field says when the call applied, and the transport
//! test that proves the row. `docs/control-plane/retry-matrix.md` is the
//! registry rendered through those rows by `quantick-app --dump-retry-matrix`,
//! the way the capability inventory beside it is rendered.
//!
//! # What is derived and what is written
//!
//! Derived from the registry, never written here: which capabilities are
//! mutable, the policy each declares, what the gateway therefore does with a
//! key, and whether any grant reaches the capability at all
//! ([`GRANTABLE_PROFILE_IDS`]). Written here, because no registry knows it:
//! which read reconciles a call. [`drift`] is what keeps the written half
//! honest against the derived half — a mutable capability with no row, a row
//! for nothing, a declared policy the descriptor no longer publishes, a
//! readback capability or scope the registry does not carry or that can
//! change state, a read with a scope or event kind it does not take, a
//! snapshot field the scope's own published schema does not have, or a
//! readback a caller granted the capability could not read. The generator
//! refuses to render while any of those stands. A journal row's field has no
//! published schema to check against — event payloads are not registered —
//! so it is proven where it is used instead: the transport tests read every
//! journal row's field back from a real event.
//!
//! # Cost
//!
//! None at run time. The table is `const` data; [`drift`] and the renderer run
//! only from `main`'s dump path, before a window exists, and from tests.

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt,
    fmt::Write as _,
};

use quantick_control::{
    handshake::ProfileAuthority,
    id::{PermissionId, ProfileId},
    registry::{
        CapabilityDescriptor, IdempotencyPolicy,
        IdempotencyPolicy::{Forbidden, Optional},
    },
};
use serde_json::Value;

use super::{
    actions::MARK_EVENT_KIND,
    analysis::DRAWINGS_SCOPE_ID,
    chart,
    contract::{ObserverContract, SNAPSHOT_CAPABILITY_ID, TRADER_PROFILE_ID},
    events::READ_CAPABILITY_ID as EVENTS_READ_CAPABILITY_ID,
    feed,
    gateway::GRANTABLE_PROFILE_IDS,
    inventory::standard_contract,
    notify::NOTIFICATION_EVENT_KIND,
    script::{SCRIPT_ATTACHED_EVENT_KIND, SCRIPT_DETACHED_EVENT_KIND},
    session::PAPER_SCOPE_ID,
    trade::TICKET_EVENT_KIND,
    workspace,
};

/// The banner the generated file opens with. Load-bearing, as the inventory's
/// is: `crates/guards` greps for it to confirm it is reading generated output.
pub(crate) const GENERATED_MARKER: &str =
    "<!-- generated by `quantick-app --dump-retry-matrix`; do not edit -->";

/// One mutable capability, and how a client reconciles a call to it whose
/// answer it never saw.
#[derive(Clone, Copy, Debug)]
pub(crate) struct Readback {
    /// The capability this row covers.
    pub capability: &'static str,
    /// The policy the descriptor is expected to publish. Not a second source
    /// of truth — the matrix renders the descriptor's own — but the tripwire:
    /// a descriptor whose policy moves without this row being revisited is
    /// [`Drift::PolicyMoved`], because the readback that suited a retryable
    /// call rarely suits one that is not.
    pub policy: IdempotencyPolicy,
    /// The read capability that shows the effect.
    pub read: &'static str,
    /// The `snapshot.read` scope, when `read` is `snapshot.read`.
    pub scope: Option<&'static str>,
    /// The journal event kind, when `read` is `events.read`.
    pub event: Option<&'static str>,
    /// The field that shows the effect: a dotted path, `[]` stepping into an
    /// array. Inside the scope's value for a snapshot, inside each event of
    /// `event`'s kind for the journal.
    pub field: &'static str,
    /// What the field says when the call applied, against a reading taken
    /// before the call.
    pub applied_when: &'static str,
    /// The transport tests that exercise this row.
    pub proven_by: &'static [&'static str],
}

const LAYOUT_TEST: &str = "a_dropped_layout_answer_is_replayed_and_the_layout_is_made_once";
/// Every reachable `optional` row, one keyed call and its retry each.
const EVERY_OPTIONAL_TEST: &str =
    "every_reachable_optional_row_replays_a_dropped_answer_and_begins_once";
/// Version 2 of the layout calls answers through the gateway, exactly.
const LAYOUT_V2_TEST: &str = "layout_v2_answers_with_the_exact_share_and_v1_is_still_there";
/// A version-1 answer the wire refuses says the call may have acted.
const LAYOUT_V1_REFUSAL_TEST: &str =
    "a_v1_layout_answer_the_wire_refuses_says_the_call_may_have_acted";
/// The feed generation moves on every respawn.
const FEED_GENERATION_TEST: &str = "the_feed_generation_advances_on_every_respawn_and_reads_back";
/// Every reachable `forbidden` row, one keyed call each.
const EVERY_FORBIDDEN_TEST: &str =
    "every_reachable_forbidden_row_refuses_a_key_before_the_application";
const UNKNOWN_OUTCOME_TEST: &str =
    "a_keyed_action_held_past_its_deadline_is_refused_as_unknown_and_reconciled_by_readback";
const FEED_TEST: &str = "a_dropped_feed_recovery_answer_is_replayed_and_the_recovery_runs_once";
const TRADE_SHAPING_TEST: &str =
    "a_dropped_trade_shaping_answer_is_replayed_and_the_ticket_changes_once";
const TRADE_UNREACHABLE_TEST: &str = "no_production_grant_reaches_a_trade_capability_keyed_or_not";
const ANNOTATION_TEST: &str = "an_interrupted_annotation_is_resolved_by_its_readback";
const MARK_TEST: &str = "an_interrupted_attention_mark_is_resolved_by_its_readback";
const SCRIPT_TEST: &str = "an_interrupted_script_attach_or_detach_is_resolved_by_its_readback";
const NOTIFY_TEST: &str = "an_interrupted_notification_is_resolved_by_its_readback";

/// A row read back through one `snapshot.read` scope.
const fn snapshot(
    capability: &'static str,
    policy: IdempotencyPolicy,
    scope: &'static str,
    field: &'static str,
    applied_when: &'static str,
    proven_by: &'static [&'static str],
) -> Readback {
    Readback {
        capability,
        policy,
        read: SNAPSHOT_CAPABILITY_ID,
        scope: Some(scope),
        event: None,
        field,
        applied_when,
        proven_by,
    }
}

/// A row read back through the journal, from a cursor taken before the call.
const fn journal(
    capability: &'static str,
    policy: IdempotencyPolicy,
    event: &'static str,
    field: &'static str,
    applied_when: &'static str,
    proven_by: &'static [&'static str],
) -> Readback {
    Readback {
        capability,
        policy,
        read: EVENTS_READ_CAPABILITY_ID,
        scope: None,
        event: Some(event),
        field,
        applied_when,
        proven_by,
    }
}

const LAYOUT_PROOF: &[&str] = &[EVERY_OPTIONAL_TEST, LAYOUT_V2_TEST];
/// Collapse is also the call the v1 refusal test drives.
const LAYOUT_COLLAPSE_PROOF: &[&str] =
    &[EVERY_OPTIONAL_TEST, LAYOUT_V2_TEST, LAYOUT_V1_REFUSAL_TEST];
/// The layout-tab calls have one version and are not called by the v2 test.
const LAYOUT_TAB_PROOF: &[&str] = &[EVERY_OPTIONAL_TEST];
const CREATED_BY_CALLER: &str = "a drawing authored by the caller, of the call's `tool_id`, that the pre-call reading lacked; the author name is not authenticated, so keep one create per tool in flight. A pane lists at most 512 drawings: when its `drawings_truncated` is set, read `events.read` `annotate.object.created` from the pre-call cursor instead";

/// Every mutable capability's readback. Order is irrelevant: the document is
/// rendered in the registry's order.
pub(crate) const READBACKS: &[Readback] = &[
    snapshot(
        "annotate.arrow.create",
        Forbidden,
        DRAWINGS_SCOPE_ID,
        "tabs[].panes[].drawings[].author.client_name",
        CREATED_BY_CALLER,
        &[ANNOTATION_TEST, EVERY_FORBIDDEN_TEST],
    ),
    snapshot(
        "annotate.label.create",
        Forbidden,
        DRAWINGS_SCOPE_ID,
        "tabs[].panes[].drawings[].author.client_name",
        CREATED_BY_CALLER,
        &[ANNOTATION_TEST, EVERY_FORBIDDEN_TEST],
    ),
    snapshot(
        "annotate.remove",
        Forbidden,
        DRAWINGS_SCOPE_ID,
        "tabs[].panes[].drawings[].drawing_id",
        "the named `annotation_id` is no longer listed; when the pane's `drawings_truncated` is set an unlisted id proves nothing, so read `events.read` `annotate.object.removed` from the pre-call cursor, which is journaled only for a removal that happened",
        &[ANNOTATION_TEST, EVERY_FORBIDDEN_TEST],
    ),
    snapshot(
        "annotate.zone.create",
        Forbidden,
        DRAWINGS_SCOPE_ID,
        "tabs[].panes[].drawings[].author.client_name",
        CREATED_BY_CALLER,
        &[ANNOTATION_TEST, EVERY_FORBIDDEN_TEST],
    ),
    journal(
        "attention.mark.create",
        Forbidden,
        MARK_EVENT_KIND,
        "payload.note",
        "an event after the pre-call cursor carries the call's own `note`; send a note unique to the call, since an unnoted mark (the trader's shortcut included) matches any other",
        &[MARK_TEST, EVERY_FORBIDDEN_TEST],
    ),
    snapshot(
        "feed.reconnect",
        Optional,
        feed::SCOPE_ID,
        "tabs[].feed_generation",
        "the tab's generation is past the pre-call reading: it took over a new feed session (a tab with nothing to respawn answers `respawned: false` and keeps its generation)",
        &[FEED_TEST, EVERY_OPTIONAL_TEST, FEED_GENERATION_TEST],
    ),
    snapshot(
        "feed.reload",
        Optional,
        feed::SCOPE_ID,
        "tabs[].feed_generation",
        "the tab's generation is past the pre-call reading: it took over a new feed session (a tab with nothing to respawn answers `respawned: false` and keeps its generation)",
        &[FEED_TEST, EVERY_OPTIONAL_TEST, FEED_GENERATION_TEST],
    ),
    // The journal rather than `analysis.indicators`: that scope carries the
    // trader's input values and needs `observe.user_text`, which a caller
    // granted the script tier does not hold by default.
    journal(
        "indicator.script.attach",
        Forbidden,
        SCRIPT_ATTACHED_EVENT_KIND,
        "payload.script.slot_id",
        "an event after the pre-call cursor names a new `slot_id`",
        &[SCRIPT_TEST, EVERY_FORBIDDEN_TEST],
    ),
    journal(
        "indicator.script.detach",
        Forbidden,
        SCRIPT_DETACHED_EVENT_KIND,
        "payload.script.slot_id",
        "an event after the pre-call cursor names the `slot_id` asked for",
        &[SCRIPT_TEST, EVERY_FORBIDDEN_TEST],
    ),
    snapshot(
        "layout.focus.set",
        Optional,
        workspace::SCOPE_ID,
        "tabs[].panes[].focused",
        "the pane at the address asked for is the focused one, per pane since two context charts share a side; the flag is reported for the active tab only, and a collapsed column reports the flow pane, so reconcile a background or collapsed tab once it is shown",
        LAYOUT_PROOF,
    ),
    // `context_collapsed`, not `panes[].visible`: a collapsed chart is still
    // counted as shown, because it comes back with its bars and drawings.
    snapshot(
        "layout.pane.collapse",
        Optional,
        workspace::SCOPE_ID,
        "tabs[].context_collapsed",
        "the tab's context column reads collapsed",
        LAYOUT_COLLAPSE_PROOF,
    ),
    snapshot(
        "layout.pane.expand",
        Optional,
        workspace::SCOPE_ID,
        "tabs[].context_collapsed",
        "the tab's context column no longer reads collapsed",
        LAYOUT_PROOF,
    ),
    snapshot(
        "layout.pane.move",
        Optional,
        workspace::SCOPE_ID,
        "tabs[].panes[].pane_id",
        "the moved pane's `pane_id` is listed at the address asked for",
        LAYOUT_PROOF,
    ),
    snapshot(
        "layout.pane.resize",
        Optional,
        workspace::SCOPE_ID,
        "tabs[].split_fraction",
        "the tab's split is the share asked for",
        LAYOUT_PROOF,
    ),
    snapshot(
        "layout.pane.set_interval",
        Optional,
        chart::SCOPE_ID,
        "panes[].bar_spec",
        "the pane's bar spec is the interval asked for; it is the spec the bars were built with, which follows a new interval within two frames on the active tab and when a background tab is next shown, so read until it settles",
        LAYOUT_PROOF,
    ),
    snapshot(
        "layout.preset.apply",
        Optional,
        workspace::SCOPE_ID,
        "tabs[].layout",
        "the tab's layout is the preset asked for",
        LAYOUT_PROOF,
    ),
    snapshot(
        "layout.tab.create",
        Optional,
        workspace::SCOPE_ID,
        "layouts[].name",
        "one more layout than the pre-call reading listed",
        &[LAYOUT_TEST, EVERY_OPTIONAL_TEST, UNKNOWN_OUTCOME_TEST],
    ),
    snapshot(
        "layout.tab.rename",
        Optional,
        workspace::SCOPE_ID,
        "layouts[].name",
        "the layout carries the name asked for",
        LAYOUT_TAB_PROOF,
    ),
    snapshot(
        "layout.tab.switch",
        Optional,
        workspace::SCOPE_ID,
        "tabs[].panes[].layout_id",
        "the pane the call named (the active tab's focused pane unless `tab_id`/`pane` say otherwise) carries the layout asked for",
        LAYOUT_TAB_PROOF,
    ),
    journal(
        "notify.popup",
        Forbidden,
        NOTIFICATION_EVENT_KIND,
        "payload.message",
        "an event after the pre-call cursor carries the call's own `message`; send one unique to the call",
        &[NOTIFY_TEST, EVERY_FORBIDDEN_TEST],
    ),
    journal(
        "notify.sound",
        Forbidden,
        NOTIFICATION_EVENT_KIND,
        "payload.message",
        "an event after the pre-call cursor carries the call's own `message`; send one unique to the call",
        &[NOTIFY_TEST, EVERY_FORBIDDEN_TEST],
    ),
    journal(
        "notify.toast",
        Forbidden,
        NOTIFICATION_EVENT_KIND,
        "payload.message",
        "an event after the pre-call cursor carries the call's own `message`; send one unique to the call",
        &[NOTIFY_TEST, EVERY_FORBIDDEN_TEST],
    ),
    journal(
        "trade.instrument.set_money",
        Optional,
        TICKET_EVENT_KIND,
        "payload.asked",
        "an event after the pre-call cursor carries the caller's input as `asked`",
        &[TRADE_UNREACHABLE_TEST],
    ),
    snapshot(
        "trade.order.bracket",
        Forbidden,
        PAPER_SCOPE_ID,
        "tabs[].working_orders[].stop_loss",
        "the named order carries the stop and target asked for",
        &[TRADE_UNREACHABLE_TEST],
    ),
    snapshot(
        "trade.order.cancel",
        Forbidden,
        PAPER_SCOPE_ID,
        "tabs[].working_orders[].order_id",
        "the named order is no longer working",
        &[TRADE_UNREACHABLE_TEST],
    ),
    snapshot(
        "trade.order.place",
        Forbidden,
        PAPER_SCOPE_ID,
        "tabs[].working_orders[].order_id",
        "an order the pre-call reading lacked is working, or a position opened",
        &[TRADE_UNREACHABLE_TEST],
    ),
    snapshot(
        "trade.risk.set",
        Optional,
        PAPER_SCOPE_ID,
        "tabs[].risk_state",
        "the ticket's risk state follows the basis asked for",
        &[TRADE_UNREACHABLE_TEST],
    ),
    snapshot(
        "trade.ruler.set",
        Optional,
        PAPER_SCOPE_ID,
        "tabs[].ruler_ticks",
        "the ruler stands at the distance the call answered with",
        &[TRADE_SHAPING_TEST, TRADE_UNREACHABLE_TEST],
    ),
    snapshot(
        "trade.strategy.select",
        Optional,
        PAPER_SCOPE_ID,
        "tabs[].armed_strategy",
        "the ticket is armed with the strategy asked for",
        &[TRADE_UNREACHABLE_TEST],
    ),
];

/// The row for `capability`, if the matrix has one.
pub(crate) fn readback(capability: &str) -> Option<&'static Readback> {
    READBACKS.iter().find(|row| row.capability == capability)
}

/// One way the written rows and the registry disagree.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) enum Drift {
    /// A mutable capability the matrix has no row for.
    Unmapped { capability: String },
    /// A row for a capability that is not registered, or that cannot change
    /// state and so needs no reconciling.
    Orphan { capability: String },
    /// Two rows for one capability.
    Duplicate { capability: String },
    /// The descriptor publishes a different policy than the row expects.
    PolicyMoved {
        capability: String,
        expected: IdempotencyPolicy,
        published: IdempotencyPolicy,
    },
    /// The row names a read capability the registry does not register.
    UnknownRead { capability: String, read: String },
    /// The row's read capability can itself change state.
    ReadNotReadOnly { capability: String, read: String },
    /// The row names a snapshot scope the registry does not register, or
    /// reads `snapshot.read` without naming one.
    UnknownScope { capability: String, scope: String },
    /// The row's read and its scope or event kind do not fit together: a
    /// snapshot needs a scope, the journal needs an event kind, neither takes
    /// the other's, and no other read has a readback grammar a client (or the
    /// transport tests) could follow.
    ReadShape { capability: String, read: String },
    /// The scope's published schema has no such field.
    FieldMissing {
        capability: String,
        scope: String,
        field: String,
    },
    /// No profile the contract defines holds the capability's permissions.
    NoCeiling { capability: String },
    /// A caller granted the capability could not read its readback: the
    /// read needs a permission beyond the capability's own and the default
    /// read grant (or, for a capability no grant reaches, beyond the ceiling
    /// that holds it). A readback that needs a sensitive scope the trader
    /// never ticked reconciles nothing for the client that needs it.
    ReadbackOutOfReach { capability: String, profile: String },
}

impl fmt::Display for Drift {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unmapped { capability } => write!(
                f,
                "`{capability}` is mutable and has no row: add its readback to READBACKS"
            ),
            Self::Orphan { capability } => write!(
                f,
                "a row covers `{capability}`, which is not a registered mutable capability"
            ),
            Self::Duplicate { capability } => write!(f, "two rows cover `{capability}`"),
            Self::PolicyMoved {
                capability,
                expected,
                published,
            } => write!(
                f,
                "`{capability}` now publishes {published:?}, the row expects {expected:?}: \
                 revisit its readback before updating the row"
            ),
            Self::UnknownRead { capability, read } => write!(
                f,
                "the row for `{capability}` reads back through `{read}`, which is not registered"
            ),
            Self::ReadNotReadOnly { capability, read } => write!(
                f,
                "the row for `{capability}` reads back through `{read}`, which is not read-only"
            ),
            Self::UnknownScope { capability, scope } => write!(
                f,
                "the row for `{capability}` names snapshot scope `{scope}`, which is not registered"
            ),
            Self::ReadShape { capability, read } => write!(
                f,
                "the row for `{capability}` reads back through `{read}` with a scope or event \
                 kind that read does not take: `snapshot.read` names a scope, `events.read` an \
                 event kind, and nothing else is a readback"
            ),
            Self::FieldMissing {
                capability,
                scope,
                field,
            } => write!(
                f,
                "the row for `{capability}` names `{field}`, which the `{scope}` schema does not carry"
            ),
            Self::NoCeiling { capability } => write!(
                f,
                "no profile the contract defines holds every permission `{capability}` requires"
            ),
            Self::ReadbackOutOfReach {
                capability,
                profile,
            } => write!(
                f,
                "a `{profile}` caller granted `{capability}` and the default reads cannot read \
                 its readback"
            ),
        }
    }
}

/// Every profile, lowest ceiling first: the three a grant can hand out, then
/// the one nothing hands out. The first whose ceiling holds a capability's
/// permissions is the one that reaches it.
fn profiles_in_ceiling_order() -> impl Iterator<Item = &'static str> {
    GRANTABLE_PROFILE_IDS
        .into_iter()
        .chain(std::iter::once(TRADER_PROFILE_ID))
}

/// The lowest profile whose ceiling admits `capability`, and whether a grant
/// can hand that profile out.
fn holder(contract: &ObserverContract, capability: &CapabilityDescriptor) -> Option<Holder> {
    profiles_in_ceiling_order().find_map(|id| {
        let ceiling = ceiling(contract, id)?;
        capability
            .required_permissions
            .is_subset(&ceiling)
            .then(|| Holder {
                profile: id,
                grantable: GRANTABLE_PROFILE_IDS.contains(&id),
                ceiling,
            })
    })
}

struct Holder {
    profile: &'static str,
    grantable: bool,
    ceiling: BTreeSet<PermissionId>,
}

fn ceiling(contract: &ObserverContract, profile: &str) -> Option<BTreeSet<PermissionId>> {
    let id = ProfileId::new(profile).ok()?;
    contract.registry().permission_ceiling(&id)
}

/// Every disagreement between `rows` and the registry `contract` serves.
///
/// Takes the rows as a parameter rather than reading [`READBACKS`] so a test
/// can hand it a mutated table and watch each check bite.
pub(crate) fn drift(rows: &[Readback], contract: &ObserverContract) -> Vec<Drift> {
    let registry = contract.registry();
    // Every version of a capability shares its row: a new version changes
    // what a call carries, not how a lost one is reconciled, and each version
    // is checked against the row on its own.
    let mut mutable: BTreeMap<&str, Vec<&CapabilityDescriptor>> = BTreeMap::new();
    for descriptor in registry
        .capabilities()
        .filter(|descriptor| !descriptor.read_only)
    {
        mutable
            .entry(descriptor.id.as_str())
            .or_default()
            .push(descriptor);
    }
    let mut findings = Vec::new();
    let mut seen = BTreeMap::<&str, usize>::new();
    for row in rows {
        *seen.entry(row.capability).or_default() += 1;
    }
    for (capability, count) in &seen {
        if *count > 1 {
            findings.push(Drift::Duplicate {
                capability: (*capability).to_owned(),
            });
        }
    }
    for capability in mutable.keys() {
        if !seen.contains_key(capability) {
            findings.push(Drift::Unmapped {
                capability: (*capability).to_owned(),
            });
        }
    }
    for row in rows {
        let Some(versions) = mutable.get(row.capability) else {
            findings.push(Drift::Orphan {
                capability: row.capability.to_owned(),
            });
            continue;
        };
        for descriptor in versions {
            for finding in row_drift(row, descriptor, contract) {
                if !findings.contains(&finding) {
                    findings.push(finding);
                }
            }
        }
    }
    findings
}

fn row_drift(
    row: &Readback,
    descriptor: &CapabilityDescriptor,
    contract: &ObserverContract,
) -> Vec<Drift> {
    let capability = row.capability.to_owned();
    let mut findings = Vec::new();
    if descriptor.idempotency != row.policy {
        findings.push(Drift::PolicyMoved {
            capability: capability.clone(),
            expected: row.policy,
            published: descriptor.idempotency,
        });
    }
    let Some(read) = contract
        .registry()
        .capabilities()
        .find(|candidate| candidate.id.as_str() == row.read)
    else {
        findings.push(Drift::UnknownRead {
            capability,
            read: row.read.to_owned(),
        });
        return findings;
    };
    if !read.read_only {
        findings.push(Drift::ReadNotReadOnly {
            capability: capability.clone(),
            read: row.read.to_owned(),
        });
    }
    let shape_fits = match row.read {
        SNAPSHOT_CAPABILITY_ID => row.event.is_none(),
        EVENTS_READ_CAPABILITY_ID => row.scope.is_none() && row.event.is_some(),
        _ => false,
    };
    if !shape_fits {
        findings.push(Drift::ReadShape {
            capability: capability.clone(),
            read: row.read.to_owned(),
        });
    }
    let mut needed = read.required_permissions.clone();
    if row.read == SNAPSHOT_CAPABILITY_ID {
        let scope_id = row.scope.unwrap_or("");
        match contract.snapshot_scope(scope_id) {
            None => findings.push(Drift::UnknownScope {
                capability: capability.clone(),
                scope: scope_id.to_owned(),
            }),
            Some(scope) => {
                if !schema_has_path(&scope.schema, row.field) {
                    findings.push(Drift::FieldMissing {
                        capability: capability.clone(),
                        scope: scope_id.to_owned(),
                        field: row.field.to_owned(),
                    });
                }
                needed.extend(scope.required_permissions.iter().cloned());
            }
        }
    }
    match holder(contract, descriptor) {
        None => findings.push(Drift::NoCeiling { capability }),
        Some(holder) if !needed.is_subset(&readable(contract, descriptor, &holder)) => {
            findings.push(Drift::ReadbackOutOfReach {
                capability,
                profile: holder.profile.to_owned(),
            });
        }
        Some(_) => {}
    }
    findings
}

/// What a caller granted `capability` can read without asking the trader for
/// anything more: the capability's own permissions and the default read
/// grant. A capability no grant reaches has no such caller yet, so its
/// readback is held to the ceiling that would admit it.
fn readable(
    contract: &ObserverContract,
    capability: &CapabilityDescriptor,
    holder: &Holder,
) -> BTreeSet<PermissionId> {
    if !holder.grantable {
        return holder.ceiling.clone();
    }
    let mut readable = contract.default_grant();
    readable.extend(capability.required_permissions.iter().cloned());
    readable
}

/// The permissions a row's readback needs: its read capability's, and its
/// snapshot scope's when it names one.
fn read_needs(contract: &ObserverContract, row: &Readback) -> BTreeSet<PermissionId> {
    let mut needed = contract
        .registry()
        .capabilities()
        .find(|candidate| candidate.id.as_str() == row.read)
        .map(|read| read.required_permissions.clone())
        .unwrap_or_default();
    if let Some(scope) = row.scope.and_then(|scope| contract.snapshot_scope(scope)) {
        needed.extend(scope.required_permissions.iter().cloned());
    }
    needed
}

/// Whether a JSON schema carries `path` — dotted properties, `[]` stepping
/// into an array's items — following `$ref`s into the schema's own `$defs`
/// and trying every branch of an `anyOf`, `oneOf` or `allOf`.
///
/// The scope's published schema is the one a client validates against, so a
/// field it lacks is a field no client can read, whatever the Rust struct
/// happens to hold today.
pub(crate) fn schema_has_path(schema: &Value, path: &str) -> bool {
    let mut nodes = vec![schema];
    for segment in path.split('.') {
        let (name, into_array) = match segment.strip_suffix("[]") {
            Some(name) => (name, true),
            None => (segment, false),
        };
        let mut next = Vec::new();
        for node in nodes {
            for object in branches(schema, node, 0) {
                let Some(property) = object.get("properties").and_then(|map| map.get(name)) else {
                    continue;
                };
                if into_array {
                    next.extend(
                        branches(schema, property, 0)
                            .into_iter()
                            .filter_map(|array| array.get("items")),
                    );
                } else {
                    next.push(property);
                }
            }
        }
        if next.is_empty() {
            return false;
        }
        nodes = next;
    }
    true
}

/// How many `$ref` and combinator hops the schema walk follows before it
/// gives up. The published scope schemas nest a handful deep; the bound exists
/// only so a recursive schema cannot loop, not to fit any real one.
const MAX_SCHEMA_HOPS: usize = 16;

/// `node` with its `$ref` resolved and its combinators flattened, bounded by
/// [`MAX_SCHEMA_HOPS`].
fn branches<'a>(root: &'a Value, node: &'a Value, depth: usize) -> Vec<&'a Value> {
    if depth > MAX_SCHEMA_HOPS {
        return Vec::new();
    }
    if let Some(reference) = node.get("$ref").and_then(Value::as_str) {
        return root
            .pointer(reference.trim_start_matches('#'))
            .map(|target| branches(root, target, depth + 1))
            .unwrap_or_default();
    }
    let mut out = vec![node];
    for combinator in ["anyOf", "oneOf", "allOf"] {
        if let Some(options) = node.get(combinator).and_then(Value::as_array) {
            for option in options {
                out.extend(branches(root, option, depth + 1));
            }
        }
    }
    out
}

/// Render the committed contents of `docs/control-plane/retry-matrix.md`, or
/// say why the rows and the registry disagree.
pub(crate) fn retry_matrix_markdown() -> Result<String, String> {
    let contract = standard_contract()?;
    let findings = drift(READBACKS, &contract);
    if !findings.is_empty() {
        let lines: Vec<String> = findings.iter().map(ToString::to_string).collect();
        return Err(format!(
            "the retry matrix disagrees with the registry:\n  {}",
            lines.join("\n  ")
        ));
    }
    Ok(render(&contract))
}

/// What the gateway does with a key for this capability.
fn enforced(policy: IdempotencyPolicy, grantable: bool) -> &'static str {
    match (grantable, policy) {
        (false, _) => "refused before dispatch: no grant reaches it",
        (true, IdempotencyPolicy::Optional) => "deduplicated per connection",
        (true, IdempotencyPolicy::Required) => "key required; deduplicated per connection",
        (true, IdempotencyPolicy::Forbidden) => "key refused; not retryable, read back",
    }
}

fn policy_name(policy: IdempotencyPolicy) -> &'static str {
    match policy {
        IdempotencyPolicy::Forbidden => "forbidden",
        IdempotencyPolicy::Optional => "optional",
        IdempotencyPolicy::Required => "required",
    }
}

struct RenderedRow<'a> {
    /// The newest registered version, whose policy and reach the row shows.
    descriptor: &'a CapabilityDescriptor,
    /// Every registered version, oldest first.
    versions: Vec<u32>,
    row: &'static Readback,
    holder: Holder,
}

fn render(contract: &ObserverContract) -> String {
    // The registry iterates by `(id, version)`, so the last descriptor seen
    // for an id is its newest version.
    let mut newest: BTreeMap<&str, (&CapabilityDescriptor, Vec<u32>)> = BTreeMap::new();
    for descriptor in contract
        .registry()
        .capabilities()
        .filter(|descriptor| !descriptor.read_only)
    {
        let entry = newest
            .entry(descriptor.id.as_str())
            .or_insert((descriptor, Vec::new()));
        entry.0 = descriptor;
        entry.1.push(descriptor.version);
    }
    let registered = newest.len();
    let rows: Vec<RenderedRow<'_>> = newest
        .into_values()
        .filter_map(|(descriptor, versions)| {
            Some(RenderedRow {
                descriptor,
                versions,
                row: readback(descriptor.id.as_str())?,
                holder: holder(contract, descriptor)?,
            })
        })
        .collect();
    let mut out = String::new();
    out.push_str("# Control plane retry matrix\n\n");
    out.push_str(GENERATED_MARKER);
    out.push_str("\n\n");
    out.push_str(PREAMBLE);
    out.push_str(&summary(&rows));
    out.push_str(&table(contract, &rows));
    let _ = write!(
        out,
        "\n{registered} mutable capabilities registered, {} with a readback.\n",
        rows.len()
    );
    out
}

const PREAMBLE: &str = concat!(
    "What a client does when a call that changes something did not answer:\n",
    "retry it under the same idempotency key, or read the state back. One row\n",
    "per mutable capability the running application registers; read-only\n",
    "capabilities change nothing and need no reconciling.\n",
    "\n",
    "This file is generated; a hand edit is a guard failure, not a correction.\n",
    "The rows live in `crates/app/src/control/retry_matrix.rs`, and the\n",
    "generator refuses to render while any of them disagrees with the registry.\n",
    "To change a row, change the table or the capability and regenerate:\n",
    "\n",
    "```sh\n",
    "cargo run -p quantick-app -- --dump-retry-matrix \\\n",
    "  > docs/control-plane/retry-matrix.md\n",
    "```\n",
    "\n",
    "`cargo test -p quantick-app retry_matrix` compares this file with the\n",
    "generator and every row with the registry; `cargo test -p quantick-guards`\n",
    "compares it with the [capability inventory](capability-inventory.md) in a\n",
    "second.\n",
    "\n",
    "## Reading a row\n",
    "\n",
    "**Versions** lists every registered version of the capability; the row\n",
    "holds for all of them, and **Policy** and **Reach** are the newest's. Call\n",
    "the newest: a version is added when the previous one's contract had to\n",
    "change, and the older one is kept only so an existing client does not\n",
    "break.\n",
    "\n",
    "**Policy** is the `idempotency` the descriptor publishes. **Enforced** is\n",
    "what the gateway does with it:\n",
    "\n",
    "- *deduplicated per connection* — a call carrying an idempotency key is\n",
    "  recorded against the connection that made it. The same key with the same\n",
    "  input answers the first call's recorded outcome without acting again; the\n",
    "  same key with different input is `control.idempotency_conflict`; a retry\n",
    "  that arrives while the first call is still running is\n",
    "  `control.request_in_progress` (retryable — ask again). A call the\n",
    "  application began and had still not answered a full request window after\n",
    "  its deadline records a non-retryable `control.timeout` whose next step is\n",
    "  to read the state back: its outcome is unknown, and retrying the key cannot\n",
    "  learn it.\n",
    "- *key refused; not retryable, read back* — a call carrying a key is\n",
    "  refused before dispatch (`control.invalid_request`). Sending the call\n",
    "  twice acts twice, so a client whose call did not answer reads the state\n",
    "  back instead.\n",
    "- *refused before dispatch: no grant reaches it* — the capability's\n",
    "  ceiling is one no grant hands out, so no connection can call it, keyed or\n",
    "  not. The row records what its readback will be when that changes.\n",
    "\n",
    "**Reach** is the lowest profile whose ceiling admits the capability.\n",
    "Every readback is readable by a connection granted the capability's own\n",
    "permissions and the default read grant (the generator refuses a row that\n",
    "is not), so reconciling never needs a scope the trader did not already\n",
    "tick for the call. A capability no grant reaches is held to its ceiling\n",
    "instead, and its row says which further scope its readback needs.\n",
    "**Readback** is the read that shows the effect — a `snapshot.read` scope,\n",
    "or `events.read` filtered to one journal event kind — and **Field** the\n",
    "path within it, `[]` stepping into an array. **Applied when** says what the\n",
    "field shows if the call took effect. **Proven by** names the transport\n",
    "tests, in `crates/app/src/app/tests/retry_readback_tests.rs`, that exercise\n",
    "the row through the real local gateway.\n",
    "\n",
    "To reconcile, take the reading *before* the call — the scope's value, or\n",
    "an `events.read` cursor at `latest` — and compare it with the same read\n",
    "afterwards. A snapshot read can be retried freely: reads are read-only.\n",
    "\n",
    "## The guarantee ends with the connection\n",
    "\n",
    "Deduplication is scoped to the connection that made the call. A client\n",
    "that reconnects arrives as a new principal, and its keys are new keys: the\n",
    "same key re-executes rather than replaying. That is deliberate — the only\n",
    "identities that survive a reconnect are the bearer token, which every\n",
    "client of one grant shares, and a client-supplied name nothing\n",
    "authenticates, and scoping records by either would let one client replay\n",
    "another's answer. Widening it needs a durable client identity the\n",
    "handshake proves, which is a contract change tracked in\n",
    "[#362](https://github.com/milocaetano/quantick/issues/362). Until then a\n",
    "client whose connection dropped with a call in flight reconciles *every*\n",
    "row — `optional` ones included — through its readback, never by retrying\n",
    "the key on the new connection.\n",
    "\n",
);

fn summary(rows: &[RenderedRow<'_>]) -> String {
    let mut out = String::new();
    out.push_str("## Coverage\n\n");
    let mut classes = BTreeMap::<&str, usize>::new();
    for row in rows {
        *classes
            .entry(enforced(row.descriptor.idempotency, row.holder.grantable))
            .or_default() += 1;
    }
    let _ = writeln!(out, "| Enforced | Capabilities |");
    let _ = writeln!(out, "| --- | --- |");
    for (class, count) in &classes {
        let _ = writeln!(out, "| {class} | {count} |");
    }
    let _ = writeln!(out, "| **Total** | **{}** |\n", rows.len());
    out
}

fn table(contract: &ObserverContract, rows: &[RenderedRow<'_>]) -> String {
    let mut out = String::new();
    out.push_str("## Capabilities\n\n");
    let _ = writeln!(
        out,
        "| Capability | Versions | Policy | Enforced | Reach | Readback | Field | Applied when | \
         Proven by |"
    );
    let _ = writeln!(
        out,
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"
    );
    for rendered in rows {
        let row = rendered.row;
        let reach = if rendered.holder.grantable {
            format!("`{}`", rendered.holder.profile)
        } else {
            format!("none (`{}` ceiling)", rendered.holder.profile)
        };
        let mut source = match (row.scope, row.event) {
            (Some(scope), _) => format!("`{}` `{scope}`", row.read),
            (None, Some(event)) => format!("`{}` `{event}`", row.read),
            (None, None) => format!("`{}`", row.read),
        };
        let mut granted = contract.default_grant();
        granted.extend(rendered.descriptor.required_permissions.iter().cloned());
        let beyond: Vec<String> = read_needs(contract, row)
            .difference(&granted)
            .map(|permission| format!("`{}`", permission.as_str()))
            .collect();
        if !beyond.is_empty() {
            let _ = write!(source, " (also needs {})", beyond.join(", "));
        }
        let proof = row
            .proven_by
            .iter()
            .map(|test| format!("`{test}`"))
            .collect::<Vec<_>>()
            .join(", ");
        let versions = rendered
            .versions
            .iter()
            .map(u32::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} | {} | `{}` | {} | {} |",
            rendered.descriptor.id.as_str(),
            versions,
            policy_name(rendered.descriptor.idempotency),
            enforced(rendered.descriptor.idempotency, rendered.holder.grantable),
            reach,
            source,
            row.field,
            row.applied_when,
            proof,
        );
    }
    out
}

/// Whether a grant the gateway can hand out reaches `capability` — the rows
/// the transport tests iterate over, decided the way the document decides
/// them rather than by a prefix a test would have to keep in step.
#[cfg(test)]
pub(crate) fn reachable_by_a_grant(capability: &str) -> bool {
    let contract = standard_contract().expect("the registry builds");
    contract
        .registry()
        .capabilities()
        .find(|descriptor| descriptor.id.as_str() == capability)
        .and_then(|descriptor| holder(&contract, descriptor))
        .is_some_and(|holder| holder.grantable)
}

#[cfg(test)]
#[path = "retry_matrix_tests.rs"]
mod tests;
