//! `docs/control-plane/ui-behaviour-matrix.md`, rendered from the table.
//!
//! The same arrangement the capability inventory uses, for the same reason:
//! a document written beside the code is a document that stops agreeing with
//! it. `quantick-app --dump-ui-behaviour-matrix` writes this file, a test
//! below compares the committed copy against the generator byte for byte, and
//! a second test compares the table against the interface and the control
//! registry. The committed file can therefore be read as true, which is the
//! only thing that makes it worth committing.

use std::fmt::Write as _;

use super::registry::{NOT_A_BEHAVIOUR, PENDING_ISSUE, UI_BEHAVIOURS};
use super::{ExclusionClass, Mapping, Source};

/// The banner the generated file opens with.
///
/// Load-bearing rather than decorative, exactly as the capability inventory's
/// is: a guard greps for it to confirm it is reading a generated file rather
/// than a hand-written one that happens to share the path.
pub(crate) const GENERATED_MARKER: &str =
    "<!-- generated by `quantick-app --dump-ui-behaviour-matrix`; do not edit -->";

/// The committed contents of `docs/control-plane/ui-behaviour-matrix.md`.
///
/// Deterministic by construction: it is a `const` slice rendered in its own
/// order, so two runs on the same tree cannot disagree and the committed copy
/// can be compared byte for byte instead of parsed.
pub(crate) fn ui_behaviour_matrix_markdown() -> String {
    let mut out = String::new();
    out.push_str("# Supported UI behaviour matrix\n\n");
    out.push_str(GENERATED_MARKER);
    out.push_str("\n\n");
    out.push_str(&preamble());
    out.push_str(&summary());
    out.push_str(&rows());
    out.push_str(&appendix());
    out
}

fn preamble() -> String {
    let mut out = String::new();
    out.push_str(concat!(
        "Every behaviour a trader can reach from the interface, and either the\n",
        "control-plane capability that performs it or the recorded reason none\n",
        "does. `CLAUDE.md`'s *Operable without a hand* is the rule this answers:\n",
        "no capability ships reachable by mouse alone.\n",
        "\n",
        "This file is generated; a hand edit is a guard failure, not a\n",
        "correction. To change a row, change the table and regenerate:\n",
        "\n",
        "```sh\n",
        "cargo run -p quantick-app -- --dump-ui-behaviour-matrix \\\n",
        "  > docs/control-plane/ui-behaviour-matrix.md\n",
        "```\n",
        "\n",
        "The table lives in `crates/app/src/operability/registry.rs`; the guard\n",
        "that compares it against the interface and against the capability\n",
        "registry lives beside it, and runs as\n",
        "`cargo test -p quantick-app operability`.\n",
        "\n",
        "**Reach** names every door into the behaviour — a toolbar button, a menu\n",
        "entry and a hotkey are three doors into one room, and the row is the\n",
        "room. **Capability** is the identifier an operator invokes, from\n",
        "[the capability inventory](capability-inventory.md); more than one where\n",
        "the control plane splits what the interface joins. **Exclusion** is the\n",
        "class and the reason where no capability performs it.\n",
        "\n",
        "The three exclusion classes are closed:\n",
        "\n",
        "- `authority` — a ceiling refuses it on purpose. The reason cites the\n",
        "  ceiling, and \"why not add it\" is answered there.\n",
        "- `ui_only_by_decision` — an explicit product decision that the gesture\n",
        "  stays the trader's. The reason cites where that decision is written.\n",
        "- `pending_capability` — nothing refuses it and nobody has built it. The\n",
        "  only class that is a debt, and every row in it is tracked in\n",
    ));
    let _ = writeln!(out, "  {PENDING_ISSUE}.\n");
    out
}

fn summary() -> String {
    let mut out = String::new();
    out.push_str("## Coverage\n\n");
    let total = UI_BEHAVIOURS.len();
    let mapped = UI_BEHAVIOURS
        .iter()
        .filter(|behaviour| matches!(behaviour.mapping, Mapping::Capabilities(_)))
        .count();
    let _ = writeln!(out, "| Outcome | Behaviours |");
    let _ = writeln!(out, "| --- | --- |");
    let _ = writeln!(out, "| Reachable by capability | {mapped} |");
    for class in ExclusionClass::ALL {
        let count = UI_BEHAVIOURS
            .iter()
            .filter(|behaviour| {
                matches!(behaviour.mapping, Mapping::Excluded { class: found, .. } if found == class)
            })
            .count();
        let _ = writeln!(out, "| Excluded: `{}` | {count} |", class.as_str());
    }
    let _ = writeln!(out, "| **Total** | **{total}** |");
    out.push('\n');

    let walked = UI_BEHAVIOURS
        .iter()
        .filter(|behaviour| !behaviour.keys.is_empty())
        .count();
    let _ = writeln!(
        out,
        "{walked} of the {total} rows claim at least one registry entry, so the drift guard \
         fails when the interface changes under them. The remaining {} are gestures and panel \
         fields that no registry stands behind — a drag on a splitter, a number typed into the \
         ticket — carried in the table because a trader names them, and listed under \
         `authored` below.\n",
        total - walked
    );
    out
}

fn rows() -> String {
    let mut out = String::new();
    out.push_str("## Behaviours\n\n");
    let _ = writeln!(
        out,
        "| Behaviour | What it does | Reach | Capability | Exclusion |"
    );
    let _ = writeln!(out, "| --- | --- | --- | --- | --- |");
    for behaviour in UI_BEHAVIOURS {
        let (capability, exclusion) = match behaviour.mapping {
            Mapping::Capabilities(ids) => (
                ids.iter()
                    .map(|id| format!("`{id}`"))
                    .collect::<Vec<_>>()
                    .join(", "),
                "—".to_owned(),
            ),
            Mapping::Excluded { class, reason } => {
                ("—".to_owned(), format!("`{}` — {reason}", class.as_str()))
            }
        };
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {capability} | {exclusion} |",
            behaviour.id, behaviour.title, behaviour.reach
        );
    }
    out.push('\n');
    out
}

fn appendix() -> String {
    let mut out = String::new();
    out.push_str("## Appendix: sources the guard walks\n\n");
    out.push_str(concat!(
        "Which registry each row is held up by, and how many rows it holds. A\n",
        "source with rows is a place where adding an entry and forgetting the\n",
        "matrix fails the build.\n\n",
    ));
    let _ = writeln!(out, "| Source | Claims |");
    let _ = writeln!(out, "| --- | --- |");
    for source in Source::ALL {
        let claims = if source.is_walked() {
            UI_BEHAVIOURS
                .iter()
                .flat_map(|behaviour| behaviour.keys.iter())
                .filter(|(found, _)| *found == source)
                .count()
        } else {
            UI_BEHAVIOURS
                .iter()
                .filter(|behaviour| behaviour.keys.is_empty())
                .count()
        };
        let _ = writeln!(out, "| `{}` | {claims} |", source.as_str());
    }
    out.push('\n');

    out.push_str("## Appendix: registry entries that are not behaviours\n\n");
    out.push_str(concat!(
        "Entries the guard sees and no row claims, because a row would be a\n",
        "lie: a submenu that holds other entries and performs nothing itself, a\n",
        "capture hook that opens a menu, a \"nothing was clicked\" variant. Each\n",
        "carries its reason so a reader who disagrees has something to\n",
        "disagree with.\n\n",
    ));
    let _ = writeln!(out, "| Source | Entry | Why not a behaviour |");
    let _ = writeln!(out, "| --- | --- | --- |");
    for (source, key, reason) in NOT_A_BEHAVIOUR {
        let _ = writeln!(out, "| `{}` | `{key}` | {reason} |", source.as_str());
    }
    let _ = writeln!(out, "\n{} entries.", NOT_A_BEHAVIOUR.len());
    out
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::super::{Drift, Registered, drift, registered_capability_ids, sources};
    use super::*;

    fn committed_path() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(std::path::Path::parent)
            .expect("crates/app sits two levels below the workspace root")
            .join("docs/control-plane/ui-behaviour-matrix.md")
    }

    /// The authoritative check on the document: the committed file is what the
    /// generator emits today, byte for byte.
    #[test]
    fn the_committed_matrix_is_what_the_generator_emits() {
        let path = committed_path();
        let committed = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));
        assert_eq!(
            committed,
            ui_behaviour_matrix_markdown(),
            "the committed UI behaviour matrix is stale. Regenerate it:\n  \
             cargo run -p quantick-app -- --dump-ui-behaviour-matrix > \
             docs/control-plane/ui-behaviour-matrix.md"
        );
    }

    /// The authoritative check on the table: every behaviour the interface
    /// registers has a row, every row claims something that exists, and every
    /// capability a row names is registered.
    ///
    /// This is the test an agent adding a hotkey or a drawing tool will see
    /// fail, so it prints every finding rather than the first.
    #[test]
    fn the_matrix_covers_every_registered_behaviour() {
        let capabilities = registered_capability_ids().expect("the control registry builds");
        let findings = drift(
            UI_BEHAVIOURS,
            &sources::registered(),
            NOT_A_BEHAVIOUR,
            &capabilities,
        );
        assert!(
            findings.is_empty(),
            "the UI behaviour matrix and the interface disagree:\n{}",
            findings
                .iter()
                .map(|finding| format!("  - {}", finding.message()))
                .collect::<Vec<_>>()
                .join("\n")
        );
    }

    /// The drift fixture: a behaviour registered with no row is named, not
    /// tolerated.
    ///
    /// It registers a drawing tool that does not exist rather than adding a
    /// real one, so the guard is proven to fail without the proof itself
    /// shipping a tool nobody asked for. The same comparison runs here and in
    /// the test above; only the input differs.
    #[test]
    fn a_registered_behaviour_with_no_row_is_drift() {
        let capabilities = registered_capability_ids().expect("the control registry builds");
        let mut registered = sources::registered();
        registered.push(Registered::new(Source::DrawingTool, "fixture-tool"));

        let findings = drift(UI_BEHAVIOURS, &registered, NOT_A_BEHAVIOUR, &capabilities);
        assert_eq!(
            findings,
            vec![Drift::Unclaimed {
                source: Source::DrawingTool,
                key: "fixture-tool".to_owned(),
            }],
            "a tool registered with no matrix row has to be the only finding, and has to be one"
        );
        assert!(
            findings[0].message().contains("fixture-tool"),
            "the message names the entry: {}",
            findings[0].message()
        );
    }

    /// The other half of the fixture: a row naming a capability the control
    /// registry does not have is drift too. That is how the matrix goes stale
    /// when a capability is renamed or withdrawn rather than when a button is
    /// added.
    #[test]
    fn a_row_naming_an_unregistered_capability_is_drift() {
        let mut capabilities = registered_capability_ids().expect("the control registry builds");
        let withdrawn = "attention.mark.create";
        assert!(
            capabilities.remove(withdrawn),
            "the fixture withdraws a capability that exists today"
        );

        let findings = drift(
            UI_BEHAVIOURS,
            &sources::registered(),
            NOT_A_BEHAVIOUR,
            &capabilities,
        );
        assert_eq!(
            findings,
            vec![Drift::UnknownCapability {
                behaviour: "attention.mark.create",
                capability: withdrawn.to_owned(),
            }],
            "withdrawing a capability has to leave exactly the rows that named it failing"
        );
    }

    /// A row claiming a registry entry that no longer exists is drift from the
    /// other direction — the matrix describing an interface that is gone.
    #[test]
    fn a_row_claiming_a_departed_entry_is_drift() {
        let capabilities = registered_capability_ids().expect("the control registry builds");
        let registered: Vec<Registered> = sources::registered()
            .into_iter()
            .filter(|entry| !(entry.source == Source::DrawingTool && entry.key == "brush"))
            .collect();

        let findings = drift(UI_BEHAVIOURS, &registered, NOT_A_BEHAVIOUR, &capabilities);
        assert_eq!(
            findings,
            vec![Drift::Orphan {
                behaviour: "tool.brush",
                source: Source::DrawingTool,
                key: "brush".to_owned(),
            }],
            "removing a tool has to leave its row failing"
        );
    }

    /// Every row is legible on its own: an identifier that reads like a
    /// capability id, a title, a reach, and — where it is excluded — a reason
    /// long enough to argue with.
    ///
    /// A generator that dropped a column would still pass the byte comparison
    /// above, because that test regenerates the file it compares against.
    #[test]
    fn every_row_carries_an_identifier_a_title_a_reach_and_a_reason() {
        for behaviour in UI_BEHAVIOURS {
            assert!(
                !behaviour.id.is_empty()
                    && behaviour
                        .id
                        .chars()
                        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || "._-".contains(c)),
                "behaviour id is not a dotted lowercase identifier: {}",
                behaviour.id
            );
            assert!(!behaviour.title.is_empty(), "{} has no title", behaviour.id);
            assert!(!behaviour.reach.is_empty(), "{} has no reach", behaviour.id);
            if let Mapping::Excluded { reason, .. } = behaviour.mapping {
                assert!(
                    reason.len() > 40,
                    "{}'s exclusion reason is too short to argue with: {reason}",
                    behaviour.id
                );
            }
        }
    }

    /// The rendered document carries the marker, the regeneration command and
    /// a row for every behaviour.
    #[test]
    fn the_rendered_matrix_carries_the_marker_and_every_row() {
        let markdown = ui_behaviour_matrix_markdown();
        assert!(markdown.contains(GENERATED_MARKER), "no generated marker");
        assert!(
            markdown.contains("--dump-ui-behaviour-matrix"),
            "the document does not say how to regenerate itself"
        );
        for behaviour in UI_BEHAVIOURS {
            assert!(
                markdown.contains(&format!("| `{}` |", behaviour.id)),
                "{} has no row in the rendered matrix",
                behaviour.id
            );
        }
    }

    /// A hygiene check the drift function performs and nothing else would:
    /// two rows may not claim the same registry entry, and a row may not claim
    /// an `authored` key.
    #[test]
    fn the_guard_catches_a_contested_claim() {
        let capabilities: BTreeSet<String> = BTreeSet::new();
        let rows = [
            super::super::UiBehaviour {
                id: "fixture.one",
                title: "One",
                reach: "nowhere",
                keys: &[(Source::Hotkey, "FIXTURE_SHORTCUT")],
                mapping: Mapping::Excluded {
                    class: ExclusionClass::PendingCapability,
                    reason: "a fixture, long enough for the legibility check to accept it",
                },
            },
            super::super::UiBehaviour {
                id: "fixture.two",
                title: "Two",
                reach: "nowhere",
                keys: &[(Source::Hotkey, "FIXTURE_SHORTCUT")],
                mapping: Mapping::Excluded {
                    class: ExclusionClass::PendingCapability,
                    reason: "a fixture, long enough for the legibility check to accept it",
                },
            },
        ];
        let registered = [Registered::new(Source::Hotkey, "FIXTURE_SHORTCUT")];
        let findings = drift(&rows, &registered, &[], &capabilities);
        assert_eq!(
            findings,
            vec![Drift::DuplicateClaim {
                source: Source::Hotkey,
                key: "FIXTURE_SHORTCUT".to_owned(),
                behaviours: ["fixture.one", "fixture.two"],
            }]
        );
    }
}
