//! The guard that makes a generated file stay generated.
//!
//! Two indexes in this repository are produced from the code rather than
//! written beside it: `docs/control-plane/capability-inventory.md`, emitted by
//! `quantick-app --dump-capability-inventory`, and the hook registry under
//! `.claude/skills/ui-harness/references/`. Generation alone does not make
//! either of them true — it makes them true *at the moment they were
//! generated*. What keeps them true afterwards is this guard failing when the
//! committed copy and the code have moved apart.
//!
//! # Why a second, weaker check exists
//!
//! `crates/app` holds the authoritative comparison: a test there builds the
//! real registry and asserts the committed file equals what the generator
//! would emit today, byte for byte. Nothing here can be that exact, because
//! this crate has no dependencies and therefore cannot see a registry — only
//! the source text that builds one.
//!
//! It exists anyway because the exact check is behind the slowest crate in the
//! repository. An agent who adds a capability and forgets to regenerate should
//! learn it from the one-second guard run `CLAUDE.md` asks for after a batch of
//! edits, not from CI. The two checks agree on every case either can see; this
//! one simply sees less.
//!
//! # What makes the cheap check exact anyway
//!
//! One naming rule, enforced here: every capability identifier reaches the
//! registry through a `const <NAME>_CAPABILITY_ID: &str = "…";` in
//! `crates/app/src/control/`. That was almost true already — twelve `layout.*`
//! and `feed.*` capabilities used a bare `_ID` suffix — and making it exactly
//! true was cheaper than teaching this guard a denylist of the six other
//! suffixes (`_SCOPE_ID`, `_PERMISSION_ID`, `_EVENT_KIND`, `_CONTROL_ID`,
//! `_EFFECT_ID`, `_OWNER_ID`) that also name dotted lowercase strings in that
//! directory. A denylist would have been the kind of clever that silently
//! stops matching; a single suffix either matches or does not.
//!
//! So the delta this guard reports is the true delta, not an approximation of
//! it — for capabilities. It cannot see a capability registered from a string
//! literal written inline, which is why the authoritative test still runs.
//!
//! # The hook side closes a loop the first version left open
//!
//! Hooks are checked in three directions, not two, and the third is the one
//! that matters: a `QUANTICK_*` the application **reads** must be declared.
//! Comparing declarations against prose alone left the worst case invisible —
//! a brand-new read declares nothing and is described nowhere, so both sets
//! agreed and the guard passed a hook that existed and could not be found.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use crate::{Finding, workspace_root};

/// The committed generated inventory.
pub const INVENTORY_PATH: &str = "docs/control-plane/capability-inventory.md";

/// Where the capability identifiers are declared.
const CONTROL_DIR: &str = "crates/app/src/control";

/// The generated hook registry a session loads.
pub const REGISTRY_PATH: &str = ".claude/skills/ui-harness/references/hook-registry.md";

/// The authored half the registry is generated from.
pub const PROSE_PATH: &str = "docs/ui-harness/hook-prose.md";

/// Where the `declare_hooks!` declarations live.
const APP_SRC: &str = "crates/app/src";

/// Where the shared not-a-hook table is declared.
const HOOKS_MODULE: &str = "crates/app/src/hooks.rs";

/// The marker the generator writes and a hand-written file will not have.
const GENERATED_MARKER: &str =
    "<!-- generated by `quantick-app --dump-capability-inventory`; do not edit -->";

/// The marker the generated hook registry carries.
const REGISTRY_MARKER: &str =
    "<!-- generated by `quantick-app --dump-hook-registry`; do not edit -->";

const REMEDY_REGENERATE: &str = "Regenerate the inventory instead of editing it: \
     `cargo run -p quantick-app -- --dump-capability-inventory > \
     docs/control-plane/capability-inventory.md`, then commit the result.";

const REMEDY_MARKER: &str = "The generated inventory lost its marker line. \
     Regenerate it with `cargo run -p quantick-app -- --dump-capability-inventory` \
     rather than restoring the line by hand — a file missing the marker has \
     usually been edited elsewhere too.";

/// Every violation across the repository.
pub fn check(root: &Path) -> Vec<Finding> {
    let mut findings = Vec::new();
    check_inventory(root, &mut findings);
    check_hooks(root, &mut findings);
    findings
}

/// Every violation this guard can attribute to one edited file.
///
/// The comparison is between a document and a directory of sources, so no
/// single file carries the answer. Rather than stay silent — the failure mode
/// this crate's own guards are written against — an edit to either side re-runs
/// the whole check, which costs a few milliseconds and reports the real state.
pub fn check_file(path: &Path, _contents: &str) -> Vec<Finding> {
    let relative = path.to_string_lossy().replace('\\', "/");
    let relevant = relative.ends_with(INVENTORY_PATH)
        || relative.contains(CONTROL_DIR)
        || relative.ends_with(PROSE_PATH)
        || relative.ends_with(REGISTRY_PATH)
        || relative.contains(APP_SRC);
    if !relevant {
        return Vec::new();
    }
    check(&workspace_root())
}

fn check_inventory(root: &Path, findings: &mut Vec<Finding>) {
    let path = root.join(INVENTORY_PATH);
    let Ok(document) = std::fs::read_to_string(&path) else {
        findings.push(Finding::new(
            format!("{INVENTORY_PATH}: missing — the generated capability inventory is not there"),
            REMEDY_REGENERATE,
        ));
        return;
    };

    if !document.contains(GENERATED_MARKER) {
        findings.push(Finding::new(
            format!("{INVENTORY_PATH}: no generated-by marker; this file must not be hand-written"),
            REMEDY_MARKER,
        ));
    }

    let documented = documented_capabilities(&document);
    let declared = declared_capabilities(root);

    for (id, line) in &documented {
        if !declared.contains_key(id) {
            findings.push(Finding::new(
                format!(
                    "{INVENTORY_PATH}:{line}: `{id}` is documented but no \
                     `*_CAPABILITY_ID` constant under {CONTROL_DIR} declares it"
                ),
                REMEDY_REGENERATE,
            ));
        }
    }
    for (id, site) in &declared {
        if !documented.contains_key(id) {
            findings.push(Finding::new(
                format!("{site}: `{id}` is registered but has no row in {INVENTORY_PATH}"),
                REMEDY_REGENERATE,
            ));
        }
    }

    // A hand edit that adds or deletes a row usually leaves the footer behind,
    // and the footer is cheap to check. It catches the edit the set comparison
    // above cannot: a row whose identifier is right and whose other columns
    // were rewritten by hand still moves the count if a row was duplicated.
    if let Some(claimed) = footer_count(&document)
        && claimed != documented.len()
    {
        findings.push(Finding::new(
            format!(
                "{INVENTORY_PATH}: the footer claims {claimed} capabilities but the \
                 table has {} rows",
                documented.len()
            ),
            REMEDY_REGENERATE,
        ));
    }
}

const REMEDY_HOOKS: &str = "Every `QUANTICK_*` the application reads owes a \
     `declare_hooks!` entry beside the read and a row in \
     docs/ui-harness/hook-prose.md, and nothing else may claim to be a hook. \
     Fix whichever half is wrong, then regenerate: `cargo run -p quantick-app \
     -- --dump-hook-registry > \
     .claude/skills/ui-harness/references/hook-registry.md`. A variable under \
     the prefix that is genuinely not a launch hook goes on ALLOWLIST in \
     crates/guards/src/generated.rs, with the reason.";

/// The hook registry's two halves must name the same set, and the generated
/// file must be generated.
///
/// This is the check that would have caught `QUANTICK_DRAWING_MANAGER`: a row
/// naming a variable nothing reads, which made a capture run look like a
/// broken surface rather than a typo.
fn check_hooks(root: &Path, findings: &mut Vec<Finding>) {
    let registry_path = root.join(REGISTRY_PATH);
    match std::fs::read_to_string(&registry_path) {
        Ok(registry) if !registry.contains(REGISTRY_MARKER) => findings.push(Finding::new(
            format!("{REGISTRY_PATH}: no generated-by marker; this file must not be hand-written"),
            REMEDY_HOOKS,
        )),
        Ok(_) => {}
        Err(_) => findings.push(Finding::new(
            format!("{REGISTRY_PATH}: missing — the generated hook registry is not there"),
            REMEDY_HOOKS,
        )),
    }

    let Ok(prose) = std::fs::read_to_string(root.join(PROSE_PATH)) else {
        findings.push(Finding::new(
            format!("{PROSE_PATH}: missing — the authored half of the hook registry is not there"),
            REMEDY_HOOKS,
        ));
        return;
    };

    let allowed = not_hooks(root);
    if allowed.is_empty() {
        findings.push(Finding::new(
            format!(
                "{HOOKS_MODULE}: the `NOT_HOOKS` table is missing or unreadable — the guard                  cannot tell a deliberate non-hook from an undeclared one"
            ),
            REMEDY_HOOKS,
        ));
    }
    let described: BTreeSet<String> = hook_names(&prose);
    let declared = declared_hooks(root);

    for (name, site) in &declared {
        if !described.contains(name) && !allowed.contains(name) {
            findings.push(Finding::new(
                format!(
                    "{site}: `{name}` is declared as a hook but {PROSE_PATH} never mentions it"
                ),
                REMEDY_HOOKS,
            ));
        }
    }
    // The direction that closes the loop. Without it a *new* read declares
    // nothing, is described nowhere, and both comparisons above stay silent —
    // which is precisely the hook that exists and cannot be found, the defect
    // this whole guard was written against.
    for (name, site) in read_hooks(root) {
        if !declared.contains_key(&name) && !allowed.contains(&name) {
            findings.push(Finding::new(
                format!(
                    "{site}: `{name}` is read by the application but no `declare_hooks!` \
                     declares it — it would reach no registry and no reader"
                ),
                REMEDY_HOOKS,
            ));
        }
    }

    for name in &described {
        if !declared.contains_key(name) && !allowed.contains(name) {
            findings.push(Finding::new(
                format!(
                    "{PROSE_PATH}: `{name}` is described but no `declare_hooks!` in {APP_SRC} \
                     declares it — a capture setting it would reach nothing"
                ),
                REMEDY_HOOKS,
            ));
        }
    }
}

/// Every `QUANTICK_*` the shipped application names, with where it names it.
///
/// String literals in production code, which catches the two shapes a read
/// takes here: `env::var("QUANTICK_X")` directly, and the indirection through
/// a `const FOO_ENV: &str = "QUANTICK_X"` that several modules prefer. A name
/// appearing only in a comment is not a read and is not collected.
///
/// `#[cfg(test)] mod` blocks are skipped whole. Three variables live in them
/// and are not launch hooks; without this they would demand harness rows
/// describing hooks a release build never reads.
fn read_hooks(root: &Path) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let mut files = Vec::new();
    collect_rust_files(&root.join(APP_SRC), &mut files);
    files.sort();
    for file in files {
        let Ok(source) = std::fs::read_to_string(&file) else {
            continue;
        };
        let relative = file
            .strip_prefix(root)
            .unwrap_or(&file)
            .to_string_lossy()
            .replace('\\', "/");
        if is_test_source(&relative) {
            continue;
        }
        for (line_number, line) in production_lines(&source) {
            for name in literal_hook_names(line) {
                out.entry(name)
                    .or_insert_with(|| format!("{relative}:{line_number}"));
            }
        }
    }
    out
}

/// The lines of a source file that a release build compiles, numbered from 1.
///
/// Brace-counted rather than parsed: a `#[cfg(test)]` attribute opens a region
/// that ends when the braces it opened close again. Crude, and right for the
/// shape this repository actually writes — one `#[cfg(test)] mod tests` per
/// file, at the end.
fn production_lines(source: &str) -> Vec<(usize, &str)> {
    let mut out = Vec::new();
    let mut depth: i32 = 0;
    let mut skipping = false;
    let mut opened = false;
    for (index, line) in source.lines().enumerate() {
        if !skipping && line.trim_start().starts_with("#[cfg(test)]") {
            skipping = true;
            opened = false;
            depth = 0;
            continue;
        }
        if skipping {
            depth += line.matches('{').count() as i32;
            depth -= line.matches('}').count() as i32;
            if line.contains('{') {
                opened = true;
            }
            // A braced item ends when its braces balance. A brace-less one --
            // `#[cfg(test)] mod tests;`, `#[cfg(test)] use ...;` -- ends at its
            // own semicolon, and treating it as if it opened a block would
            // swallow the whole rest of the file, which is how a read below it
            // would escape the scan entirely.
            if (opened && depth <= 0) || (!opened && line.trim_end().ends_with(';')) {
                skipping = false;
            }
            continue;
        }
        out.push((index + 1, line));
    }
    out
}

/// Every `QUANTICK_*` inside a double-quoted literal on one line.
///
/// A name in a `//` comment is documentation, not a read, so the comment tail
/// is cut first. Quote counting is deliberately simple: the literals this
/// looks for are plain names with no escapes.
fn literal_hook_names(line: &str) -> BTreeSet<String> {
    let code = match line.find("//") {
        Some(at) if line[..at].matches('"').count().is_multiple_of(2) => &line[..at],
        _ => line,
    };
    let mut out = BTreeSet::new();
    let mut rest = code;
    while let Some(open) = rest.find('"') {
        let after = &rest[open + 1..];
        let Some(close) = after.find('"') else { break };
        // `"QUANTICK_"` with nothing after it is the prefix the diagnostic
        // filters on, not the name of a hook.
        out.extend(
            hook_names(&after[..close])
                .into_iter()
                .filter(|name| name.len() > "QUANTICK_".len()),
        );
        rest = &after[close + 1..];
    }
    out
}

/// The `QUANTICK_*` names the application itself declares as not-a-hook.
///
/// Parsed out of `crates/app/src/hooks.rs` rather than copied here. The table
/// is read at runtime by the startup diagnostic, so it has to live in the
/// application; this crate has no dependencies and cannot link it, and a
/// second copy kept in step by hand is the failure this guard exists to catch.
/// `crates/guards/tests/session_gap_agreement.rs` is the same pattern.
fn not_hooks(root: &Path) -> BTreeSet<String> {
    let Ok(source) = std::fs::read_to_string(root.join(HOOKS_MODULE)) else {
        return BTreeSet::new();
    };
    let Some(start) = source.find("const NOT_HOOKS:") else {
        return BTreeSet::new();
    };
    let table = match source[start..].find("];") {
        Some(end) => &source[start..start + end],
        None => &source[start..],
    };
    let mut out = BTreeSet::new();
    for line in table.lines() {
        for name in literal_hook_names(line) {
            out.insert(name);
        }
    }
    out
}

/// Whether a source file holds tests rather than shipped code.
///
/// `crates/app` keeps whole modules of tests in `src/**/tests/` and in files
/// suffixed `_tests.rs`, neither of which a release build compiles. A
/// `QUANTICK_*` named in one is a fixture, not a hook, and demanding a harness
/// row for it would document something that does not exist.
fn is_test_source(relative: &str) -> bool {
    relative.contains("/tests/") || relative.ends_with("_tests.rs")
}

/// Every hook name a `declare_hooks!` or `MAIN_HOOKS` declaration carries,
/// with the `path:line` of the declaration.
fn declared_hooks(root: &Path) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let mut files = Vec::new();
    collect_rust_files(&root.join(APP_SRC), &mut files);
    files.sort();
    for file in files {
        let Ok(source) = std::fs::read_to_string(&file) else {
            continue;
        };
        let relative = file
            .strip_prefix(root)
            .unwrap_or(&file)
            .to_string_lossy()
            .replace('\\', "/");
        // A declaration may wrap across lines, so the scan runs over the whole
        // file and attributes each name to the line its literal sits on.
        let mut inside = false;
        for (index, line) in source.lines().enumerate() {
            // `hooks.rs` documents the macro with a worked example. A name in a
            // doc comment is an illustration, not a declaration, and counting
            // it would let a prose row for a hook nothing declares pass.
            if line.trim_start().starts_with("///") || line.trim_start().starts_with("//!") {
                continue;
            }
            if line.contains("declare_hooks![") || line.contains("const MAIN_HOOKS") {
                inside = true;
            }
            if inside {
                for name in hook_names(line) {
                    out.entry(name)
                        .or_insert_with(|| format!("{relative}:{}", index + 1));
                }
                if line.contains("];") {
                    inside = false;
                }
            }
        }
    }
    out
}

/// Every `QUANTICK_*` named in a chunk of text.
fn hook_names(text: &str) -> BTreeSet<String> {
    let bytes = text.as_bytes();
    let mut out = BTreeSet::new();
    let mut index = 0;
    while let Some(offset) = text[index..].find("QUANTICK_") {
        let start = index + offset;
        let mut end = start;
        while end < bytes.len()
            && (bytes[end].is_ascii_uppercase()
                || bytes[end].is_ascii_digit()
                || bytes[end] == b'_')
        {
            end += 1;
        }
        out.insert(text[start..end].to_owned());
        index = end;
    }
    out
}

/// The identifiers the committed table claims, with the line each is on.
fn documented_capabilities(document: &str) -> BTreeMap<String, usize> {
    let mut out = BTreeMap::new();
    for (index, line) in document.lines().enumerate() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("| `") {
            continue;
        }
        if let Some(id) = trimmed
            .strip_prefix("| `")
            .and_then(|rest| rest.split('`').next())
            && is_capability_id(id)
        {
            out.insert(id.to_owned(), index + 1);
        }
    }
    out
}

/// The identifiers the sources declare, with the `path:line` each sits at.
fn declared_capabilities(root: &Path) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let mut files = Vec::new();
    collect_rust_files(&root.join(CONTROL_DIR), &mut files);
    files.sort();
    for file in files {
        let Ok(source) = std::fs::read_to_string(&file) else {
            continue;
        };
        let relative = file
            .strip_prefix(root)
            .unwrap_or(&file)
            .to_string_lossy()
            .replace('\\', "/");
        for (index, line) in source.lines().enumerate() {
            if let Some(id) = capability_constant(line) {
                out.insert(id, format!("{relative}:{}", index + 1));
            }
        }
    }
    out
}

/// The string a `const …_CAPABILITY_ID: &str = "…";` line declares.
///
/// Deliberately literal about the shape rather than tokenising: the constants
/// are written by hand in one consistent form, and a parser this guard cannot
/// afford to depend on is not worth the reach it would buy.
fn capability_constant(line: &str) -> Option<String> {
    let trimmed = line.trim_start();
    let rest = trimmed
        .strip_prefix("pub(crate) const ")
        .or_else(|| trimmed.strip_prefix("pub const "))
        .or_else(|| trimmed.strip_prefix("const "))?;
    let (name, tail) = rest.split_once(':')?;
    if !name.trim_end().ends_with("_CAPABILITY_ID") {
        return None;
    }
    let value = tail.split_once('=')?.1.trim();
    let literal = value.strip_prefix('"')?.split('"').next()?;
    is_capability_id(literal).then(|| literal.to_owned())
}

/// The identifier grammar: dotted, lowercase, at least two segments.
fn is_capability_id(candidate: &str) -> bool {
    candidate.contains('.')
        && candidate.split('.').all(|segment| {
            !segment.is_empty()
                && segment.chars().all(|character| {
                    character.is_ascii_lowercase() || character.is_ascii_digit() || character == '_'
                })
        })
}

/// The count the generated footer states, if the footer is intact.
fn footer_count(document: &str) -> Option<usize> {
    document
        .lines()
        .find_map(|line| line.strip_suffix(" capabilities registered."))
        .and_then(|count| count.trim().parse().ok())
}

fn collect_rust_files(directory: &Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rust_files(&path, out);
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            out.push(path);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_committed_inventory_matches_the_registered_capabilities() {
        let findings = check(&workspace_root());
        assert!(
            findings.is_empty(),
            "the generated capability inventory has drifted from the registry:\n{}",
            findings
                .iter()
                .map(|finding| finding.line.as_str())
                .collect::<Vec<_>>()
                .join("\n")
        );
    }

    #[test]
    fn a_capability_constant_is_recognised_by_its_suffix_alone() {
        assert_eq!(
            capability_constant("const PLACE_CAPABILITY_ID: &str = \"trade.order.place\";"),
            Some("trade.order.place".to_owned())
        );
        assert_eq!(
            capability_constant("pub(crate) const READ_CAPABILITY_ID: &str = \"evidence.read\";"),
            Some("evidence.read".to_owned())
        );
    }

    /// The six suffixes that also name dotted lowercase strings in the control
    /// directory, each of which the guard must ignore. This is the test that
    /// stops the guard from reporting an event kind as a missing capability.
    #[test]
    fn the_neighbouring_constant_kinds_are_not_capabilities() {
        for line in [
            "const PLACE_EVENT_KIND: &str = \"trade.order.placed\";",
            "const TAPE_SCOPE_ID: &str = \"orderflow.tape\";",
            "const EVENTS_PERMISSION_ID: &str = \"observe.events\";",
            "const FEED_CHIP_CONTROL_ID: &str = \"feed_status.chip\";",
            "const RECOVER_EFFECT_ID: &str = \"cockpit.recover\";",
            "const TOOLBAR_LAYERS_OWNER_ID: &str = \"toolbar.layers\";",
        ] {
            assert_eq!(capability_constant(line), None, "{line}");
        }
    }

    /// A capability identifier may carry a digit, and dropping one is worse
    /// than reporting it wrongly: `is_capability_id` is applied to *both* the
    /// documented and the declared side, so a name it rejects vanishes from
    /// each and the two then compare equal. Real drift on `orderflow.l2.read`
    /// — `orderflow.l2` is already a registered scope — would have passed this
    /// guard in silence.
    #[test]
    fn an_identifier_with_a_digit_is_still_an_identifier() {
        assert!(is_capability_id("orderflow.l2.read"));
        assert_eq!(
            capability_constant("const L2_CAPABILITY_ID: &str = \"orderflow.l2.read\";"),
            Some("orderflow.l2.read".to_owned())
        );
    }

    /// A hook read but declared nowhere is the defect the whole guard exists
    /// for, and the first version of it could not see the case at all: it
    /// compared declarations against prose, so a brand-new read appeared in
    /// neither set and both comparisons stayed silent.
    #[test]
    fn a_read_that_declares_nothing_is_visible_to_the_scan() {
        assert!(
            literal_hook_names("    std::env::var(\"QUANTICK_NEW\").ok()").contains("QUANTICK_NEW")
        );
        assert!(
            literal_hook_names("const SETTINGS_ENV: &str = \"QUANTICK_VIA_CONST\";")
                .contains("QUANTICK_VIA_CONST")
        );
    }

    /// The bare prefix is what the diagnostic filters on, not a hook.
    #[test]
    fn the_bare_prefix_is_not_a_hook_name() {
        assert!(literal_hook_names("name.starts_with(\"QUANTICK_\")").is_empty());
    }

    /// A name in a comment is documentation, not a read.
    #[test]
    fn a_name_in_a_comment_is_not_a_read() {
        assert!(literal_hook_names("// pair with QUANTICK_BOOK_AUTOSTART").is_empty());
        assert!(literal_hook_names("let x = 1; // see \"QUANTICK_MENTIONED\"").is_empty());
    }

    /// Test modules are skipped whole: three `QUANTICK_*` live in them and are
    /// not launch hooks.
    #[test]
    fn a_cfg_test_module_is_not_production() {
        let source = "fn real() {}
#[cfg(test)]
mod tests {
    const X: &str = \"QUANTICK_FIXTURE\";
}
";
        let lines: Vec<&str> = production_lines(source)
            .into_iter()
            .map(|(_, l)| l)
            .collect();
        assert!(lines.iter().any(|l| l.contains("fn real")));
        assert!(!lines.iter().any(|l| l.contains("QUANTICK_FIXTURE")));
    }

    /// A brace-less `#[cfg(test)]` item ends at its own semicolon.
    ///
    /// `crates/app/src/app.rs` ends with a bare `#[cfg(test)] mod tests;`.
    /// Treating that as the opening of a block left the skip latched on for
    /// the rest of the file, so every read below it escaped the scan — silently,
    /// which is the only kind of guard failure that matters.
    #[test]
    fn a_brace_less_cfg_test_item_does_not_swallow_the_rest_of_the_file() {
        let source = "#[cfg(test)]
mod tests;

fn after() -> bool {
    std::env::var(\"QUANTICK_BELOW_THE_ATTRIBUTE\").is_ok()
}
";
        let seen: Vec<&str> = production_lines(source)
            .into_iter()
            .map(|(_, l)| l)
            .collect();
        assert!(
            seen.iter()
                .any(|l| l.contains("QUANTICK_BELOW_THE_ATTRIBUTE")),
            "a read below a brace-less #[cfg(test)] item must still be scanned"
        );
        assert!(!seen.iter().any(|l| l.contains("mod tests;")));
    }

    /// A braced test module is still skipped whole.
    #[test]
    fn a_braced_cfg_test_module_is_still_skipped() {
        let source = "fn real() {}

#[cfg(test)]
mod tests {
    const X: &str = \"QUANTICK_FIXTURE\";
}

fn also_real() -> bool {
    std::env::var(\"QUANTICK_AFTER_THE_MODULE\").is_ok()
}
";
        let seen: Vec<&str> = production_lines(source)
            .into_iter()
            .map(|(_, l)| l)
            .collect();
        assert!(!seen.iter().any(|l| l.contains("QUANTICK_FIXTURE")));
        assert!(seen.iter().any(|l| l.contains("QUANTICK_AFTER_THE_MODULE")));
    }

    /// The two directories `crates/app` keeps whole test modules in.
    #[test]
    fn test_sources_are_recognised_by_path() {
        assert!(is_test_source(
            "crates/app/src/app/tests/control_plane_tests.rs"
        ));
        assert!(is_test_source("crates/app/src/app/drawings_tests.rs"));
        assert!(!is_test_source("crates/app/src/frvp.rs"));
    }

    #[test]
    fn a_row_is_read_out_of_the_generated_table() {
        let document = "\
| Capability | Version | Module | Read-only | Permissions |
| --- | --- | --- | --- | --- |
| `trade.order.place` | 1 | `trade` | no | `trade` |

1 capabilities registered.
";
        let documented = documented_capabilities(document);
        assert_eq!(documented.len(), 1);
        assert!(documented.contains_key("trade.order.place"));
        assert_eq!(footer_count(document), Some(1));
    }

    /// The header row must not be mistaken for a capability. It is the one
    /// line of the table that starts with `|` and carries no backticked id.
    #[test]
    fn the_table_header_is_not_a_capability() {
        assert!(documented_capabilities("| Capability | Version |\n").is_empty());
    }
}
