//! The guard that makes a generated file stay generated.
//!
//! Two indexes in this repository are produced from the code rather than
//! written beside it: `docs/control-plane/capability-inventory.md`, emitted by
//! `quantick-app --dump-capability-inventory`, and the hook registry under
//! `.claude/skills/ui-harness/references/`. Generation alone does not make
//! either of them true — it makes them true *at the moment they were
//! generated*. What keeps them true afterwards is this guard failing when the
//! committed copy and the code have moved apart.
//!
//! # Why a second, weaker check exists
//!
//! `crates/app` holds the authoritative comparison: a test there builds the
//! real registry and asserts the committed file equals what the generator
//! would emit today, byte for byte. Nothing here can be that exact, because
//! this crate has no dependencies and therefore cannot see a registry — only
//! the source text that builds one.
//!
//! It exists anyway because the exact check is behind the slowest crate in the
//! repository. An agent who adds a capability and forgets to regenerate should
//! learn it from the one-second guard run `CLAUDE.md` asks for after a batch of
//! edits, not from CI. The two checks agree on every case either can see; this
//! one simply sees less.
//!
//! # What makes the cheap check exact anyway
//!
//! One naming rule, enforced here: every capability identifier reaches the
//! registry through a `const <NAME>_CAPABILITY_ID: &str = "…";` in
//! `crates/app/src/control/`. That was almost true already — twelve `layout.*`
//! and `feed.*` capabilities used a bare `_ID` suffix — and making it exactly
//! true was cheaper than teaching this guard a denylist of the six other
//! suffixes (`_SCOPE_ID`, `_PERMISSION_ID`, `_EVENT_KIND`, `_CONTROL_ID`,
//! `_EFFECT_ID`, `_OWNER_ID`) that also name dotted lowercase strings in that
//! directory. A denylist would have been the kind of clever that silently
//! stops matching; a single suffix either matches or does not.
//!
//! So the delta this guard reports is the true delta, not an approximation of
//! it — for capabilities. It cannot see a capability registered from a string
//! literal written inline, which is why the authoritative test still runs.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use crate::{Finding, workspace_root};

/// The committed generated inventory.
pub const INVENTORY_PATH: &str = "docs/control-plane/capability-inventory.md";

/// Where the capability identifiers are declared.
const CONTROL_DIR: &str = "crates/app/src/control";

/// The generated hook registry a session loads.
pub const REGISTRY_PATH: &str = ".claude/skills/ui-harness/references/hook-registry.md";

/// The authored half the registry is generated from.
pub const PROSE_PATH: &str = "docs/ui-harness/hook-prose.md";

/// Where the `declare_hooks!` declarations live.
const APP_SRC: &str = "crates/app/src";

/// Environment variables under the `QUANTICK_` prefix that are deliberately
/// not launch hooks, and so owe the harness no row.
///
/// Signed, because an allowlist is how a parity guard is silently defeated:
/// every entry states what it is instead, and a reader who disagrees has
/// something to disagree with. Nothing reaches a UI surface from here.
const ALLOWLIST: &[(&str, &str)] = &[
    (
        "QUANTICK_GIT_COMMIT",
        "build metadata, read through `option_env!` at compile time and \
         reported in the control plane's system info. Setting it at runtime \
         does nothing, so a harness row would describe a hook that is not one.",
    ),
    (
        "QUANTICK_TEST_STORE_HOME_ENV",
        "test plumbing inside `store_home`'s own `#[cfg(test)]` module, which \
         lets a test redirect the store home without touching the real one. \
         Never read by a release build.",
    ),
    (
        "QUANTICK_FAKE_STORE",
        "test plumbing inside `workspace_bundle`'s own `#[cfg(test)]` module. \
         Never read by a release build.",
    ),
];

/// The marker the generator writes and a hand-written file will not have.
const GENERATED_MARKER: &str =
    "<!-- generated by `quantick-app --dump-capability-inventory`; do not edit -->";

/// The marker the generated hook registry carries.
const REGISTRY_MARKER: &str =
    "<!-- generated by `quantick-app --dump-hook-registry`; do not edit -->";

const REMEDY_REGENERATE: &str = "Regenerate the inventory instead of editing it: \
     `cargo run -p quantick-app -- --dump-capability-inventory > \
     docs/control-plane/capability-inventory.md`, then commit the result.";

const REMEDY_MARKER: &str = "The generated inventory lost its marker line. \
     Regenerate it with `cargo run -p quantick-app -- --dump-capability-inventory` \
     rather than restoring the line by hand — a file missing the marker has \
     usually been edited elsewhere too.";

/// Every violation across the repository.
pub fn check(root: &Path) -> Vec<Finding> {
    let mut findings = Vec::new();
    check_inventory(root, &mut findings);
    check_hooks(root, &mut findings);
    findings
}

/// Every violation this guard can attribute to one edited file.
///
/// The comparison is between a document and a directory of sources, so no
/// single file carries the answer. Rather than stay silent — the failure mode
/// this crate's own guards are written against — an edit to either side re-runs
/// the whole check, which costs a few milliseconds and reports the real state.
pub fn check_file(path: &Path, _contents: &str) -> Vec<Finding> {
    let relative = path.to_string_lossy().replace('\\', "/");
    let relevant = relative.ends_with(INVENTORY_PATH)
        || relative.contains(CONTROL_DIR)
        || relative.ends_with(PROSE_PATH)
        || relative.ends_with(REGISTRY_PATH)
        || relative.contains(APP_SRC);
    if !relevant {
        return Vec::new();
    }
    check(&workspace_root())
}

fn check_inventory(root: &Path, findings: &mut Vec<Finding>) {
    let path = root.join(INVENTORY_PATH);
    let Ok(document) = std::fs::read_to_string(&path) else {
        findings.push(Finding::new(
            format!("{INVENTORY_PATH}: missing — the generated capability inventory is not there"),
            REMEDY_REGENERATE,
        ));
        return;
    };

    if !document.contains(GENERATED_MARKER) {
        findings.push(Finding::new(
            format!("{INVENTORY_PATH}: no generated-by marker; this file must not be hand-written"),
            REMEDY_MARKER,
        ));
    }

    let documented = documented_capabilities(&document);
    let declared = declared_capabilities(root);

    for (id, line) in &documented {
        if !declared.contains_key(id) {
            findings.push(Finding::new(
                format!(
                    "{INVENTORY_PATH}:{line}: `{id}` is documented but no \
                     `*_CAPABILITY_ID` constant under {CONTROL_DIR} declares it"
                ),
                REMEDY_REGENERATE,
            ));
        }
    }
    for (id, site) in &declared {
        if !documented.contains_key(id) {
            findings.push(Finding::new(
                format!("{site}: `{id}` is registered but has no row in {INVENTORY_PATH}"),
                REMEDY_REGENERATE,
            ));
        }
    }

    // A hand edit that adds or deletes a row usually leaves the footer behind,
    // and the footer is cheap to check. It catches the edit the set comparison
    // above cannot: a row whose identifier is right and whose other columns
    // were rewritten by hand still moves the count if a row was duplicated.
    if let Some(claimed) = footer_count(&document)
        && claimed != documented.len()
    {
        findings.push(Finding::new(
            format!(
                "{INVENTORY_PATH}: the footer claims {claimed} capabilities but the \
                 table has {} rows",
                documented.len()
            ),
            REMEDY_REGENERATE,
        ));
    }
}

const REMEDY_HOOKS: &str = "Every `QUANTICK_*` the application reads owes a \
     `declare_hooks!` entry beside the read and a row in \
     docs/ui-harness/hook-prose.md, and nothing else may claim to be a hook. \
     Fix whichever half is wrong, then regenerate: `cargo run -p quantick-app \
     -- --dump-hook-registry > \
     .claude/skills/ui-harness/references/hook-registry.md`. A variable under \
     the prefix that is genuinely not a launch hook goes on ALLOWLIST in \
     crates/guards/src/generated.rs, with the reason.";

/// The hook registry's two halves must name the same set, and the generated
/// file must be generated.
///
/// This is the check that would have caught `QUANTICK_DRAWING_MANAGER`: a row
/// naming a variable nothing reads, which made a capture run look like a
/// broken surface rather than a typo.
fn check_hooks(root: &Path, findings: &mut Vec<Finding>) {
    let registry_path = root.join(REGISTRY_PATH);
    match std::fs::read_to_string(&registry_path) {
        Ok(registry) if !registry.contains(REGISTRY_MARKER) => findings.push(Finding::new(
            format!("{REGISTRY_PATH}: no generated-by marker; this file must not be hand-written"),
            REMEDY_HOOKS,
        )),
        Ok(_) => {}
        Err(_) => findings.push(Finding::new(
            format!("{REGISTRY_PATH}: missing — the generated hook registry is not there"),
            REMEDY_HOOKS,
        )),
    }

    let Ok(prose) = std::fs::read_to_string(root.join(PROSE_PATH)) else {
        findings.push(Finding::new(
            format!("{PROSE_PATH}: missing — the authored half of the hook registry is not there"),
            REMEDY_HOOKS,
        ));
        return;
    };

    let allowed: BTreeSet<&str> = ALLOWLIST.iter().map(|(name, _)| *name).collect();
    let described: BTreeSet<String> = hook_names(&prose);
    let declared = declared_hooks(root);

    for (name, site) in &declared {
        if !described.contains(name) && !allowed.contains(name.as_str()) {
            findings.push(Finding::new(
                format!(
                    "{site}: `{name}` is declared as a hook but {PROSE_PATH} never mentions it"
                ),
                REMEDY_HOOKS,
            ));
        }
    }
    for name in &described {
        if !declared.contains_key(name) && !allowed.contains(name.as_str()) {
            findings.push(Finding::new(
                format!(
                    "{PROSE_PATH}: `{name}` is described but no `declare_hooks!` in {APP_SRC} \
                     declares it — a capture setting it would reach nothing"
                ),
                REMEDY_HOOKS,
            ));
        }
    }
}

/// Every hook name a `declare_hooks!` or `MAIN_HOOKS` declaration carries,
/// with the `path:line` of the declaration.
fn declared_hooks(root: &Path) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let mut files = Vec::new();
    collect_rust_files(&root.join(APP_SRC), &mut files);
    files.sort();
    for file in files {
        let Ok(source) = std::fs::read_to_string(&file) else {
            continue;
        };
        let relative = file
            .strip_prefix(root)
            .unwrap_or(&file)
            .to_string_lossy()
            .replace('\\', "/");
        // A declaration may wrap across lines, so the scan runs over the whole
        // file and attributes each name to the line its literal sits on.
        let mut inside = false;
        for (index, line) in source.lines().enumerate() {
            if line.contains("declare_hooks![") || line.contains("const MAIN_HOOKS") {
                inside = true;
            }
            if inside {
                for name in hook_names(line) {
                    out.entry(name)
                        .or_insert_with(|| format!("{relative}:{}", index + 1));
                }
                if line.contains("];") {
                    inside = false;
                }
            }
        }
    }
    out
}

/// Every `QUANTICK_*` named in a chunk of text.
fn hook_names(text: &str) -> BTreeSet<String> {
    let bytes = text.as_bytes();
    let mut out = BTreeSet::new();
    let mut index = 0;
    while let Some(offset) = text[index..].find("QUANTICK_") {
        let start = index + offset;
        let mut end = start;
        while end < bytes.len()
            && (bytes[end].is_ascii_uppercase()
                || bytes[end].is_ascii_digit()
                || bytes[end] == b'_')
        {
            end += 1;
        }
        out.insert(text[start..end].to_owned());
        index = end;
    }
    out
}

/// The identifiers the committed table claims, with the line each is on.
fn documented_capabilities(document: &str) -> BTreeMap<String, usize> {
    let mut out = BTreeMap::new();
    for (index, line) in document.lines().enumerate() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("| `") {
            continue;
        }
        if let Some(id) = trimmed
            .strip_prefix("| `")
            .and_then(|rest| rest.split('`').next())
            && is_capability_id(id)
        {
            out.insert(id.to_owned(), index + 1);
        }
    }
    out
}

/// The identifiers the sources declare, with the `path:line` each sits at.
fn declared_capabilities(root: &Path) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let mut files = Vec::new();
    collect_rust_files(&root.join(CONTROL_DIR), &mut files);
    files.sort();
    for file in files {
        let Ok(source) = std::fs::read_to_string(&file) else {
            continue;
        };
        let relative = file
            .strip_prefix(root)
            .unwrap_or(&file)
            .to_string_lossy()
            .replace('\\', "/");
        for (index, line) in source.lines().enumerate() {
            if let Some(id) = capability_constant(line) {
                out.insert(id, format!("{relative}:{}", index + 1));
            }
        }
    }
    out
}

/// The string a `const …_CAPABILITY_ID: &str = "…";` line declares.
///
/// Deliberately literal about the shape rather than tokenising: the constants
/// are written by hand in one consistent form, and a parser this guard cannot
/// afford to depend on is not worth the reach it would buy.
fn capability_constant(line: &str) -> Option<String> {
    let trimmed = line.trim_start();
    let rest = trimmed
        .strip_prefix("pub(crate) const ")
        .or_else(|| trimmed.strip_prefix("pub const "))
        .or_else(|| trimmed.strip_prefix("const "))?;
    let (name, tail) = rest.split_once(':')?;
    if !name.trim_end().ends_with("_CAPABILITY_ID") {
        return None;
    }
    let value = tail.split_once('=')?.1.trim();
    let literal = value.strip_prefix('"')?.split('"').next()?;
    is_capability_id(literal).then(|| literal.to_owned())
}

/// The identifier grammar: dotted, lowercase, at least two segments.
fn is_capability_id(candidate: &str) -> bool {
    candidate.contains('.')
        && candidate.split('.').all(|segment| {
            !segment.is_empty()
                && segment
                    .chars()
                    .all(|character| character.is_ascii_lowercase() || character == '_')
        })
}

/// The count the generated footer states, if the footer is intact.
fn footer_count(document: &str) -> Option<usize> {
    document
        .lines()
        .find_map(|line| line.strip_suffix(" capabilities registered."))
        .and_then(|count| count.trim().parse().ok())
}

fn collect_rust_files(directory: &Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rust_files(&path, out);
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            out.push(path);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_committed_inventory_matches_the_registered_capabilities() {
        let findings = check(&workspace_root());
        assert!(
            findings.is_empty(),
            "the generated capability inventory has drifted from the registry:\n{}",
            findings
                .iter()
                .map(|finding| finding.line.as_str())
                .collect::<Vec<_>>()
                .join("\n")
        );
    }

    #[test]
    fn a_capability_constant_is_recognised_by_its_suffix_alone() {
        assert_eq!(
            capability_constant("const PLACE_CAPABILITY_ID: &str = \"trade.order.place\";"),
            Some("trade.order.place".to_owned())
        );
        assert_eq!(
            capability_constant("pub(crate) const READ_CAPABILITY_ID: &str = \"evidence.read\";"),
            Some("evidence.read".to_owned())
        );
    }

    /// The six suffixes that also name dotted lowercase strings in the control
    /// directory, each of which the guard must ignore. This is the test that
    /// stops the guard from reporting an event kind as a missing capability.
    #[test]
    fn the_neighbouring_constant_kinds_are_not_capabilities() {
        for line in [
            "const PLACE_EVENT_KIND: &str = \"trade.order.placed\";",
            "const TAPE_SCOPE_ID: &str = \"orderflow.tape\";",
            "const EVENTS_PERMISSION_ID: &str = \"observe.events\";",
            "const FEED_CHIP_CONTROL_ID: &str = \"feed_status.chip\";",
            "const RECOVER_EFFECT_ID: &str = \"cockpit.recover\";",
            "const TOOLBAR_LAYERS_OWNER_ID: &str = \"toolbar.layers\";",
        ] {
            assert_eq!(capability_constant(line), None, "{line}");
        }
    }

    #[test]
    fn a_row_is_read_out_of_the_generated_table() {
        let document = "\
| Capability | Version | Module | Read-only | Permissions |
| --- | --- | --- | --- | --- |
| `trade.order.place` | 1 | `trade` | no | `trade` |

1 capabilities registered.
";
        let documented = documented_capabilities(document);
        assert_eq!(documented.len(), 1);
        assert!(documented.contains_key("trade.order.place"));
        assert_eq!(footer_count(document), Some(1));
    }

    /// The header row must not be mistaken for a capability. It is the one
    /// line of the table that starts with `|` and carries no backticked id.
    #[test]
    fn the_table_header_is_not_a_capability() {
        assert!(documented_capabilities("| Capability | Version |\n").is_empty());
    }
}
